### ISSUE TITLE
Review rename attribute on percentage operation from shapefile

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1002]
The `percentage` operation usually creates more than one column on the dataset.  
Rename attribute from shapefile works different of the postigis. Moreover, there is a truncate on names limited to 10 characters.  
Adapts the function that rename to work with shapefile as well.

**Comment by pedro-andrade-inpe** [comment]
It is working properly for shape files. I believe that we only must document it very well to warn the user the shapefile limits in this case. @avancinirodrigo, ok?

**Comment by avancinirodrigo** [comment]
It would be good. The problem about this is when the user to try create a attribute that already exists in the dataset considering the truncation.
