### ISSUE TITLE
truncate attribute names for shapefile in Lua

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1007]
Do not wait for GDAL to truncate attribute names. Show a warning in this case, instead of getting a GDAL warning:

```
Warning 6: Normalized/laundered field name: 'fid_percent_of_total_area' to 'fid_
percen'
```

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, it seems not possible. If terrame show a warning before, then there are two warnings.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, but we could truncate in TerraME to avoid any warning from TerraLib or GDAL.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, the message is internal to method that create the vec2vec or raster2vec, we renamed after that.

**Comment by pedro-andrade-inpe** [comment]
Yes, it is true. We need to add this discussion to the terra lib report. #890.

**Comment by avancinirodrigo** [comment]
This issue was resolved in terralib.
The warning was already implemented in TerraME. See in Layer functional tests.
