### ISSUE TITLE
Problem with open package in main GUI on Mac

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1032]
Only `base` works.
Try to open other package to see the problem.

Error in prompt:
```
Bus error: 10
```

**Comment by pedro-andrade-inpe** [comment]
The same problem occurs with clicking in "Documentation", even for base package. It seems that the problem is in line:

```lua
_Gtme.isWindowsOS()
```

@avancinirodrigo, where is this function implemented? Is it in C++?

**Comment by pedro-andrade-inpe** [comment]
It might be a problem related to the compiler. Please @avancinirodrigo verify http://lua.2524044.n2.nabble.com/Bus-error-on-MacOS-td7648901.html
