### ISSUE TITLE
Create layer of cells with and without box

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1039]
Implement the functionality and tests to create cells using the bounding box of the input data or not. Currently the argument exists but it is not used.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, in TerraView this argument is called `mask`.

**Comment by avancinirodrigo** [comment]
Commit https://github.com/pedro-andrade-inpe/terrame/commit/79f0aaaea1c9e78586ed3303ffaa30973350dab0 overwrited the source code related to this issue. Review and fix.
