### ISSUE TITLE
create cellular space from tiff file

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1040]
Make the functionality to create a cellular space from a tiff file.

**Comment by pedro-andrade-inpe** [comment]
related to #890.

**Comment by pedro-andrade-inpe** [comment]
Update cabeça de boi example to use tiff directly to create cells.

**Comment by avancinirodrigo** [comment]
Does not work to tif confirmed in TerraView and TerraLib API.

**Comment by pedro-andrade-inpe** [comment]
Marisa said that it is already working. @avancinirodrigo, to check this just update cabecadeboi example and create cells from the raster layer directly (and see if it calls the respective C++ code).
