### ISSUE TITLE
Review all calls related to the terralib components

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1052]
Because the problem #1051, it was necessary become terralib global on the system, which it is no longer necessary calls getPackage("terralib") and import("terralib"). It might to impact on all tests.

**Comment by pedro-andrade-inpe** [comment]
Do not forget to review `version()` in `terrame.lua`.

**Comment by avancinirodrigo** [comment]
In version() there is not problem because the version command is atomic, like execute and exit.

**Comment by avancinirodrigo** [comment]
The solution in commit https://github.com/TerraME/terrame/commit/89291d7e309a8614a818ca015a1743700379ac96 seems that doesn't work in mac. Please, it need review the terralib tests as well.
