### ISSUE TITLE
Request for Linux TerraME version

### ISSUE THREAD

**Issue by brunaezleal** [TerraME/terrame#1060]
Currently there is only Windows and MacOS TerraME 2.0 versions. But Linux version is required for my INPE-EM application. When is it going to be launched? Thanks.

**Comment by pedro-andrade-inpe** [comment]
@brunaezleal, which Linux distribution do you use?

**Comment by brunaezleal** [comment]
Ubuntu 15.10

**Comment by avancinirodrigo** [comment]
It was available release 2.0-beta-2 in `tar.gz` for while, it works in ubuntu 14, 15 and 16 versions.
