### ISSUE TITLE
forEachNeighbor stops working

### ISSUE THREAD

**Issue by vilmount** [TerraME/terrame#1065]
This code works on 29/03 alpha version:
```lua
  			forEachNeighbor(cell, function (cell, neighbor)
                          				Y = cell.past[lu]
                          				neighY = neighbor.past[lu]
                          			   
                          				if (cell[luccMEModel.landUseNoData] ~= 1) then 
                          				  Y = Y / (1 - cell[luccMEModel.landUseNoData]) 
                        				  end
                          				
                          				if (neighbor[luccMEModel.landUseNoData] ~= 1) then 
                          				  neighY = neighY / (1 - neighbor[luccMEModel.landUseNoData]) 
                        				  end
                          				
                          				if (neighbor[luccMEModel.landUseNoData] < 1) then 
                          					   count = count + 1
                          					   neighSum = neighSum + neighY
                          				end
                          		end)
```

On the alpha 3 version it does not execute (06/05).

**Comment by pedro-andrade-inpe** [comment]
@vilmount, which error did you get?

**Comment by vilmount** [comment]
The function does not execute, forward on the code I get an error because I need the Y value.

I write prints before, inside and after the forEachNeighbor function, the inside one never shows.

**Comment by pedro-andrade-inpe** [comment]
Does `cell.past[lu]` exist (not `nil`)? Did you call `CellularSpace:synchronize()` previously?

**Comment by vilmount** [comment]
cell.past[lu] exist.

Yes, I call cs:synchronize(), but before I create the neighborhood.

**Comment by pedro-andrade-inpe** [comment]
Please put here the code where you create the neighborhood.

**Comment by vilmount** [comment]
cs:createNeighborhood()

**Comment by pedro-andrade-inpe** [comment]
please add the following code before forEachNeighbor:

```lua
print(cell)
```

**Comment by vilmount** [comment]
alternate_model         number [0]
ap                      number [0]
assentamentos           number [0]
cObj_                   userdata
col                     number [0]
desmatamento            number [0]
desmatamento2011        number [0]
desmatamento2014        number [0]
dist_riobranco          number [740383.6]
fertilidadealtaoumedia  number [0]
floresta                number [0.137987]
floresta2011            number [0.137987]
floresta2014            number [0.137987]
id                      string [C00L06]
lin                     number [6]
neighborhoods           named table of size 1
object_id0              string [C00L06]
outros                  number [0.862013]
past                    named table of size 22
region                  number [1]
rios_todos              number [38480.41]
rodovias                number [128223]
spatial_data            userdata
ti                      number [0]
ti_2009                 number [0]
uc_pi                   number [0]
uc_us                   number [0]
x                       number [0]
y                       number [0]
