### ISSUE TITLE
small correction in TME_PATH [Mac]

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1077]
Implement a small correction in TME_PATH for Mac OS X. Instead of creating TME_PATH from the directory where terrame is and add "../MacOS", remove the last directory and add "MacOS", to avoid the following error in the tests:

```
Testing tests/functional/basics/FileSystem.lua
Testing chDir
Error in ...cOS/packages/base/tests/functional/basics/FileSystem.lua:52: Values should be equal, but got 
'/Applications/terrame.app/Contents/MacOS/packages' and 
'/Applications/terrame.app/Contents/bin/../MacOS/packages'.
```

**Comment by avancinirodrigo** [comment]
Maybe it is not possible, because terrame is found over /bin directory, in other words, it is relative to terrame in /bin.

**Comment by avancinirodrigo** [comment]
This is the new form of mapper terrame executable from the mac bundle. The test must adapt.

**Comment by pedro-andrade-inpe** [comment]
Just add the following command in the script:

```bash
echo "/etc1/etc2/etc3/etc" | sed -e "s/\/[^\/]*$//"
```
