### ISSUE TITLE
Shapefile doesn't accept boolean in TerraLib:saveDataSet()

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1081]
Review this alternative step.

**Comment by pedro-andrade-inpe** [comment]
I could not understand what does "does' t accept boolean" mean.

**Comment by avancinirodrigo** [comment]
It doesn't accept boolean type as attribute.

**Comment by pedro-andrade-inpe** [comment]
OK. So just convert it to string (using `tostring`) and show a `customWarning`.
