### ISSUE TITLE
Redirect stderr output

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1083]
Redirect stderr output in Mac and Windows. A simple solution for Mac would be to change the script that creates terrame to 

```
"$TME_PATH"/terrame $@ 2> /dev/null
```

Search for `c++ redirect error output` in google for a better solution that can work in different operational systems.

**Comment by avancinirodrigo** [comment]
In Windows seems that there is not solution.
Wainting for:
http://stackoverflow.com/questions/37285353/can-visual-studio-redirect-stderr-to-2nul-in-release-mode

**Comment by pedro-andrade-inpe** [comment]
Have you tried https://support.microsoft.com/en-us/kb/58667 ?
