### ISSUE TITLE
create spatial index for shapefiles

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1094]
When creating a `Layer`, add a new argument `index = true` that creates a spatial index for the shamefile if it does not exist. See the code in TerraView. When a shapefile is imported, it asks if the user wants to create such index. This makes attributeFill operations faster.

**Comment by pedro-andrade-inpe** [comment]
#890

**Comment by pedro-andrade-inpe** [comment]
Default is `true`. This operation does not take much time to execute.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, the function fill() auto add in Layer, should be put this argument in it?

**Comment by pedro-andrade-inpe** [comment]
No.
