### ISSUE TITLE
default value in Layer:fill

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1097]
In `Layer:fill`, whenever it is not possible to compute an attribute value for a given object, a default value should be used. For example, when there is no polygon within a given cell (excluding its dummy values #1095), the default value must be used. It could be zero as default, but the user might have the option to choose a different value.

**Comment by pedro-andrade-inpe** [comment]
#890.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, in terralib:attributefill() the user can set the default value.

**Comment by pedro-andrade-inpe** [comment]
This issue was already implemented and tested.
