### ISSUE TITLE
Error in Environment:loadNeighborhood() 

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1098]
The error happens in Mac, I didn't run in Windows.
Error message:
```
Testing tests/database/alternative/Environment.lua
Testing loadNeighborhood
Error in ...packages/base/tests/database/alternative/Environment.lua:248: Test expected:
  "Could not read the file properly. It seems that it is corrupted."
  got:
  "The string '' found as weight in the file '/Users/developer/terrame/build-cmake/install/terrame.app/Contents/MacOS/packages/base/data/error/gpmAreaCellsPols-error2.gpm' could not be converted to a number."
```
It could be associated to Lua 5.3.

**Comment by pedro-andrade-inpe** [comment]
In windows it works properly.

**Comment by pedro-andrade-inpe** [comment]
This is a very strange problem. It seems that `string.find` in Lua is returning a different value for Mac and for Windows. It was not an error in TerraME 1.6. It might occur because Mac is now using Lua 5.3. Let's see when Windows migrate to the newest version if this problem occurs.

**Comment by pedro-andrade-inpe** [comment]
This error also fails in exciting line `488` from `Environment`. Once it is fixed the tests should execute all source code lines from `Environment`.
