### ISSUE TITLE
data files for tests and for release

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1100]
Think and implement a strategy to separate data files for tests and for release in packages. Some files should not belong to data directory in the release as they have errors that are identified in the tests. However, the implemented strategy should be easy for developers to adapt the installed terrame to work properly with tests.

**Comment by pedro-andrade-inpe** [comment]
Note that log directories also have this problem. Possibly it could be something that could be added to the installer or as an command line option to download the remaining files necessary to have a complete test environment.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, what do you think about to separate the data physically, like data to test were on tests/data. It is a good thing in terms of uncoupling.

**Comment by pedro-andrade-inpe** [comment]
I prefer to have data/test within the package directory. This directory then could be removed when creating the installer, but it could be accessed through function `filePath`. Another possible solution is to have a package called `data` only to store data related to tests.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, questions:
There are data that belong to the test and other things, what to do?
What does happen to description.lua?

**Comment by pedro-andrade-inpe** [comment]
One initial idea would be to have `data/test`, with the data that is only used in tests. Data within a directory in `data`  must not be documented and then they could be removed from the release. What do you think?

**Comment by pedro-andrade-inpe** [comment]
In this case, `filePath` when it refers to a package and it contains a `/` in its first argument, if it could not find the file then a different message must be shown describing that the user might not be using the original source code but a release version.

**Comment by avancinirodrigo** [comment]
Associated to #813. The data need review.
