### ISSUE TITLE
Remove YgDbLUDrqQbvu7QxTYxX.xml from data of terralib package

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1105]
File `terralib/data/YgDbLUDrqQbvu7QxTYxX.xml` is necessary due to some TerraLib constraint. Find a way to get rid of this file.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, please add it to the report #890.

**Comment by avancinirodrigo** [comment]
It is associated to #880.
