### ISSUE TITLE
Problem with assertFile() for Projects

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1108]
It seems that is not guaranteed the order of data in the project. So, a file project created before is not equal than some other.
It is happening in mac, I do not tested on Windows.

**Comment by pedro-andrade-inpe** [comment]
I'll add this to #890.

**Comment by pedro-andrade-inpe** [comment]
It is possibly our error, because TerraView saves the project and loads it and the layers are shown in the same order.

**Comment by pedro-andrade-inpe** [comment]
Anyway, if it was in some way encapsulated into TerraLib/TerraView library, this problem could be avoided.

**Comment by pedro-andrade-inpe** [comment]
#1242 will help to solve this. @hguerra, please verify if the layers in the files are in the same order. If yes, possibly the only difference between the files is the `id`, and therefore this issue would be unnecessary.

**Comment by pedro-andrade-inpe** [comment]
There is no clean and feasible solution for this issue. It could work in a local machine, but not in the CI server, as we cannot guarantee that the .tview log file could be opened. Therefore, it is better to just delete such files without calling `UnitTest:assertFile`.
