### ISSUE TITLE
Predator Prey not have Time Series configuration

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1133]
This field is not found like visual test suggest. It was not tested on Windows.

**Comment by pedro-andrade-inpe** [comment]
Yes, the button to disable time series was removed from the graphical interface. I wll update the description of the visual test to close this issue. Anyway, I'll move this issue to beta-2.

**Comment by pedro-andrade-inpe** [comment]
Documentation updated.
