### ISSUE TITLE
Layer:properties()

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1165]
Implement `Layer:properties()` that returns a vector of strings with the properties of a given layer. It is necessary to solve #1119. I could find only function `propertyExists` in TerraLib.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, "properties of the layer" what would be?
Layers has info that are in project file, is this?

**Comment by pedro-andrade-inpe** [comment]
Properties are basically the names of its attributes. If there are no attributes (for example, only bands), it should return nil.
