### ISSUE TITLE
GDAL warning messages

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1200]
Verify how to avoid GDAL warnings in the screen. Investigate if it is in the GDAL compilation or in its initialisation, to avoid messages such as:

```
Warning 1: Field id of width 255 truncated to 254.
```

**Comment by hguerra** [comment]
As described in the GDAL, warnings can be avoided adding the following configuration before register all formats drivers:

```cpp
CPLPushErrorHandler(CPLQuietErrorHandler);
```
https://gitlab.dpi.inpe.br/rodrigo.avancini/terralib/blob/master/src/terralib/gdal/Module.cpp in line 96.
https://gitlab.dpi.inpe.br/rodrigo.avancini/terralib/blob/master/src/terralib/ogr/Module.cpp in line 99.
https://gitlab.dpi.inpe.br/rodrigo.avancini/terralib/blob/master/src/terralib/wfs/Module.cpp in line 68.

<b>Reference:</b>

http://osgeo-org.1560.x6.nabble.com/gdal-dev-how-to-hide-warning-information-td4632128.html
http://osgeo-org.1560.x6.nabble.com/suppressing-libtiff-warnings-td3750707.html
http://www.gdal.org/cpl__error_8h.html#ad13c9c8f2037ddfd566c2a197f7b2537
