### ISSUE TITLE
Create jenkins job to run the execution tests

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1211]
Analyze what is better way to do this test.
The steps to do this test are in:
https://github.com/TerraME/terrame/wiki/developing#Testing

I think that this job shouldn't be in pull request's flow because it is big and slow. So, jenkins allow to schedule the jobs.

**Comment by raphaelrpl** [comment]
The Jenkins execution tests job has been created. It runs every day at 10:49 PM and it is available in http://www.dpi.inpe.br/jenkins/job/terrame-test-execution-linux-ubuntu-14.04/.

**Comment by pedro-andrade-inpe** [comment]
Is there a way to the remove all the output lines starting with the following lines?

```
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension KEYBOARD
```

**Comment by raphaelrpl** [comment]
Yes, there is. I have unchecked Log option of GUI Xvfb plugin, so the next test should not display them anymore.

**Comment by pedro-andrade-inpe** [comment]
Good, the output above was removed. Is there a way to remove the installing output as well?

```
Install the project...
-- Install configuration: "Release"
-- Installing: /home/jenkins/build-projects/workspace/terrame-repository-test-linux-ubuntu-14.04/912aef2648ce2cc4e96f6d529ac186d3e6407c49/install/bin/terrame
-- Set runtime path of "/home/jenkins/build-projects/workspace/terrame-repository-test-linux-ubuntu-14.04/912aef2648ce2cc4e96f6d529ac186d3e6407c49/install/bin/terrame" to ""
-- Installing: /home/jenkins/build-projects/workspace/terrame-repository-test-linux-ubuntu-14.04/912aef2648ce2cc4e96f6d529ac186d3e6407c49/install/./bin/lua
-- Installing: /home/jenkins/build-projects/workspace/terrame-repository-test-linux-ubuntu-14.04/912aef2648ce2cc4e96f6d529ac186d3e6407c49/install/./bin/lua/utils.lua
-- Installing: /home/jenkins/build-projects/workspace/terrame-repository-test-linux-ubuntu-14.04/912aef2648ce2cc4e96f6d529ac186d3e6407c49/install/./bin/lua/doc.lua
[...]
```

It represents more than 70% of the whole output and is unnecessary.

**Comment by raphaelrpl** [comment]
Yeah, there is. I can redirect the make install output to ```/dev/null```. But, the same script of build and installation is used in Linux compilation job in Jenkins. Would you like also to hide it from that job?

**Comment by pedro-andrade-inpe** [comment]
Yes, but as long as if you guarantee that errors will be shown.

**Comment by raphaelrpl** [comment]
Sure, i will redirect everything to ```/dev/null``` except stderr.

**Comment by pedro-andrade-inpe** [comment]
Both execution and repository tests are being executed nightly. However, I am getting emails only from repository tests, but not execution tests.

**Comment by raphaelrpl** [comment]
Oh yes, there is not a Post build action set. I have unmarked for testing schedule to avoid spawn emails. The option has been set again.

**Comment by pedro-andrade-inpe** [comment]
Just to be clear: the idea is to send emails only if execution tests or repository tests fail. If both fail two emails can be sent. In the next day, if the tests are ok then a confirmation will be sent to say that the problem was fixed. In the next day, if everything is ok then no email will be sent.
