### ISSUE TITLE
Layer:export

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1217]
Allow exporting a Layer into a different format. Think about the required parameters for this function.

**Comment by pedro-andrade-inpe** [comment]
For example, one could export a tiff Layer into a NetCDF file.

**Comment by pedro-andrade-inpe** [comment]
For now, it will only be necessary to implement the following usage:

```lua
layer:export{file = "myfile.shp"}
layer:export{file = "myfile.geojson"}
```

The arguments need to be named because in the future we can add more parameters.

**Comment by pedro-andrade-inpe** [comment]
@hguerra, is it ok for you?

**Comment by hguerra** [comment]
it may be interesting can re-project CRS like GDAL does:

GDAL code:
```
ogr2ogr output.shp -t_srs "EPSG:4326" input.shp
````
```lua
layer:export{file = "myfile.shp"}
layer:export{file = "myfile.geojson"}
layer:export{file = "myfile.geojson", crs = "EPSG:4326"}
```
Once that many frameworks define a specific CRS to use, mostly WGS84 lat/lon.

**Comment by pedro-andrade-inpe** [comment]
@hguerra, in fact this is another requirement. We have not worked with projections yet. I will add another issue for this.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, is the exported layer must go to "project.tview" (to be a layer)?
