### ISSUE TITLE
Layer with GeoJSON file

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1218]
Allow importing GeoJSON files into Layers in the same way shapefiles work.

**Comment by hguerra** [comment]
When trying to importing GeoJSON files into Layers using OGR

ERROR 4: GeoJSON Driver doesn't support update.

```lua
local function makeAndOpenDataSource(connInfo, type)
	local ds = binding.te.da.DataSourceFactory.make(type)

	ds:setConnectionInfo(connInfo)
	ds:open() -- error

	return ds
end
```
