### ISSUE TITLE
UniTest:assertFile add argument error

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1242]
Add a third argument to `UnitTest:assertFile` that indicates a percentage of characters that can be different from the output and the log.

**Comment by pedro-andrade-inpe** [comment]
This function is necessary as .tview files are always different because of the id of layers.

```
id="459ec3be-fa57-4b74-9daf-8e9e21c036b1"
```

Diff should only be used if there is no error. Otherwise, TerraME must read the files line by line and compare each character to count the difference.

**Comment by pedro-andrade-inpe** [comment]
Instead of using `diff` command to check the differences between files, open both files and compare them character by character, and compute the percentage of the differences between them. This will be useful to stop the errors of .tview files in Jenkins tests. Implement this after closing the issue above.

**Comment by pedro-andrade-inpe** [comment]
Use `Utils: levenshtein` to compute the difference between each pair of lines.

**Comment by hguerra** [comment]
When creating a tview file with more than one layer, the DataSource are created in random order.

**Comment by hguerra** [comment]
UniTest:assertFile using 'Utils: levenshtein'

```lua
if not isFile(oldLog) then
	if not self.created_logs then -- SKIP
		self.created_logs = 0 -- SKIP
	end

	self.created_logs = self.created_logs + 1 -- SKIP
	_Gtme.printError("Creating '".._Gtme.makePathCompatibleToAllOS("log"..s..self.log..s..fname).."'.")
	os.execute("cp \""..self.tmpdir..s..fname.."\" \""..oldLog.."\"") -- SKIP
	self.test = self.test + 1 -- SKIP
	self.success = self.success + 1 -- SKIP
else
	if tol > 0 then
		local fopen = openFile(oldLog)
		local v1 = fopen:read("*all")
		closeFile(fopen)

		fopen = openFile(self.tmpdir..s..fname)
		local v2 = fopen:read("*all")
		closeFile(fopen)

		local dist = levenshtein(v1, v2)
		if dist <= tol then
			self.success = self.success + 1
		else
			self.fail = self.fail + 1
			local msg = "Values should be equal, but got \n'"..v1.."' and \n'"..v2.."'."..
					"\nThe maximum tolerance is "..tol..", but got "..dist.."."

			self:printError(msg)
		end
	else
		local result = runCommand("diff \""..self.tmpdir..s..fname.."\" \""..oldLog.."\"")

		if #result == 0 then
			self.success = self.success + 1
		else
			_Gtme.printError("Files \n  '".._Gtme.makePathCompatibleToAllOS(oldLog).."'\nand\n  '"..self.tmpdir..s..fname.."'\nare different.")
			forEachElement(result, function(_, value)
				_Gtme.printError(value)
			end)

			self.fail = self.fail + 1 -- SKIP
		end
	end
end
```
Test
```lua
local terralib = getPackage("terralib")
local projName = "cellular_layer_basic.tview"

local proj = terralib.Project{
	file = projName,
	clean = true
}

local layerName1 = "Sampa"

terralib.Layer{
	project = proj,
	name = layerName1,
	file = filePath("sampa.shp", "terralib")
}

unitTest:assertFile(projName, 96)
```

**Comment by pedro-andrade-inpe** [comment]
As this issue was a tentative for a solution of #1108 (which will not be implemented), there is no need to implement this in the next versions.

**Comment by pedro-andrade-inpe** [comment]
This issue was already solved by https://github.com/TerraME/terrame/commit/013c62d7b57d19a360fed54eec1352caf4880f3d.
