### ISSUE TITLE
TerraLib cannot have two layers from OGRGeoJSON

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1243]
When one imports a  OGR:GeoJSON file, TerraLib uses TerraLib OGRGeoJSON as the Layer's name. Therefore it is not possible to import more than one GeoJSON layer.

**Comment by avancinirodrigo** [comment]
I think that is possible to rename before add in project file.

**Comment by avancinirodrigo** [comment]
This problem impacts in #1217 as well. 
It is not possible to create more than one table in database.  
The problem can be verified in TerraLib:saveLayerAs() function.

**Comment by avancinirodrigo** [comment]
According with the title of this issue, it would be invalid. TerraLib allow add more than one geojson layer, because the layers is identified by its id, including in TerraME is working normally.
But the problem in #1217 still occurs.
