### ISSUE TITLE
Enable CMakeLists.txt to do not skip Log folder

### ISSUE THREAD

**Issue by raphaelrpl** [TerraME/terrame#1256]
Currently, CMakeLists.txt is set to skip log folder. It turns out in re-create log files during Jenkins job build.

A solution should be add a test flag (default false) to put log folder in installation path.

**Comment by pedro-andrade-inpe** [comment]
For now, it might be interesting to simply create a symbolic link with `ln -s`

**Comment by avancinirodrigo** [comment]
it was resolved by #1212.
