### ISSUE TITLE
unify log directories?

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1263]
Thinking about the continuous integration server, it might be interesting to unify the log directories into a single one, as it was in the past. Suppose a developer works in Windows and he adds a test that creates a new log file. When he creates a new pull request, the CI server will download the code and test it in Linux, but the Linux log directory does not have the new log file and therefore it will create an error in the tests that will never be solved until the user adds such file in the Linux directory. I believe it is better to have a unified directory, even if we need to increase the allowed error for each image and file created along the tests.

**Comment by pedro-andrade-inpe** [comment]
Some source code lines are not being executed because of this problem. Once this issue is fixed, `UnitTest` should not have any problems in the executed lines. The lines that are not being executed currently are:

```
Checking UnitTest.lua
Line 293 was not executed.
Line 294 was not executed.
Line 400 was not executed.
Line 402 was not executed.
Line 405 was not executed.
Line 406 was not executed.
```

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe,
Where is it made?

**Comment by pedro-andrade-inpe** [comment]
`base/lua/UnitTest.lua`

**Comment by pedro-andrade-inpe** [comment]
and `src/lua/test.lua`

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe,
If there is no log in some package, does the system have to create in /log or /log/os?

**Comment by pedro-andrade-inpe** [comment]
No. This is something that needs to be verified. The system needs to create /log or /log/os only if an assertFile or assertSnapshot is called.
