### ISSUE TITLE
Rename FileSystem to System and LogFile to Log

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1296]
`FileSystem` has functions such as `tmpDir`, `isWindowsOS`, which are more related to the `System`. `LogFile` has an argument named `file`, which would make the name `File` unnecessary.

**Comment by pedro-andrade-inpe** [comment]
`System` is not a good name. Some suggestions are `Computer` or `OperationalSystem`.

**Comment by avancinirodrigo** [comment]
I like names that already been used in other APIs, this reduce the gap of languages:
https://docs.oracle.com/javase/7/docs/api/java/lang/System.html
http://doc.qt.io/qt-5/qsysinfo.html
http://www.cplusplus.com/reference/iolibrary/
