### ISSUE TITLE
Assert condition of Project file '.tview'

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1301]
As the Lua does not guarantee the order of data in file, the test should guarantee that there is the data in file disregarding the order. This can be done iterating the elements.
A possible solution is to create a structure of data that handles XML.
Another solution is related to TerraLib provide its Project.

**Comment by pedro-andrade-inpe** [comment]
Another possible solution is, whenever assertFile gets a .tview file as argument, it opens both projects and see if they have the same layers, instead of comparing the files.

**Comment by pedro-andrade-inpe** [comment]
#1108.
