### ISSUE TITLE
Project file is created even when there is error in 'clean' argument

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1317]
The error can be found in `tests/functional/alternative/Project.lua`

```lua
		local layerShouldBeString = function()
			Project{file = "myproj.tview", cean = true}
		end
		unitTest:assertError(layerShouldBeString, incompatibleTypeMsg("cean", "string", true))

		local notFile = function()
			Project{file = "myproj.tview", cean = "true.abc"}
		end
		unitTest:assertError(notFile, "Value of argument 'cean' is not a valid file name.")
```

**Comment by pedro-andrade-inpe** [comment]
Please wait for #1316 to test this. But in the tests I am running no file is created in the tests above.

**Comment by pedro-andrade-inpe** [comment]
The tests above are commented, and so no error indicating that the files were created is prompted. When solving this issue, all source code lines of `Project.lua` must be executed (currently there is only one line that does not run: 132).
