### ISSUE TITLE
Reproject layer in Layer:export()

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1347]
Implement a function to reproject a layer. Think in an interface for this, once there are different ways to describe projections.

**Comment by avancinirodrigo** [comment]
Currently, it was not found how to do this in TerraLib. 
There is a resource that can change the layer SRS in TerraView, but it works only to visualization, the data does not change.
It needs help of terralib team.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe,
Although there is not a function to change SRS, it is possible to export a data with a new projection.
But, there are two possibilities, either create this function or add a new parameter to Layer:export() function #1217.
