### ISSUE TITLE
Create a function in File to validade a file

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1366]
Sometimes is necessary validate a file before to save it in disc, for eg. validate if the name of file is valid or the full path is valid. 
File:getFullPath() doesn't work if the file doesn't exist, because it checks if the file exist.
The function can be:
```lua
File:isValid(somePath) 
```

**Comment by pedro-andrade-inpe** [comment]
Possibly this should be verified while instantiating a `File` automatically. If one wants to check if it is valid then a `pcall` could be used.

**Comment by pedro-andrade-inpe** [comment]
Verify if the directory exists. Verify if the file name does not have any invalid character.

**Comment by pedro-andrade-inpe** [comment]
A filename cannot contain any of the following characters:

```
\ / : * ? " < > |
```

https://support.microsoft.com/en-us/kb/177506

Check in Linux and Mac as well.
