### ISSUE TITLE
checkGdal is not declared (mode=strict)

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1372]
When running TerraME in strict mode, it shows two warnings related to checkGdal:

```
[pedro@~] $ terrame -mode=strict welcome.lua 
Variable 'checkGdal' is not declared.
Variable 'checkGdal' is not declared.
```

This function is used in CellularSpace, but it is not declared! Fix it.

**Comment by hguerra** [comment]
This was solved by a3b370c3b6b28ea5fdb5e9182b6245b4674e9740
