### ISSUE TITLE
Create a job to compile terralib in jenkins

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1376]
Now, TerraLib allows fork, with this it is possible compile it before creates the terrame build.
Therefore, create a job to compile terralib.
This job must be before terrame build, the fork in gitlab is:
https://gitlab.dpi.inpe.br/rodrigo.avancini/terralib.git
This job mustn't to clear its build all the time that someone commit, it will be incremental.

**Comment by avancinirodrigo** [comment]
An important observation, it is necessary to use the release-5.1 branch.

**Comment by avancinirodrigo** [comment]
@raphaelrpl, now this job must be before terrame-build and show it on git as well.

**Comment by pedro-andrade-inpe** [comment]
This was already implemented in the CI server.
