### ISSUE TITLE
Error message not accurate in Layer with a file that does not exist

### ISSUE THREAD

**Issue by vilmount** [TerraME/terrame#1409]
Using a Layer and informing a wrong file name the error message is:

>  Error: Argument 'source' is mandatory.
> Stack traceback:
>     File amazonas.lua, line 8, in call to function 'Layer'

Code:
`l1 = Layer{
	project = proj,
	name = "layer",
	file = "D:\\paper\\paper_pol.shp"
}`

I was using the name paper.shp that doesn't exist and got the error above. Fixed the name the code works,

**Comment by pedro-andrade-inpe** [comment]
Thanks, @vilmount. We will fix this in the next version (end of this month).
