### ISSUE TITLE
Rethink about Group as action of an Event

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1421]
Currently when a `Group` is an `action` of an `Agent`, it only calls `rebuild`. Think about what more could be executed, such as `randomise` or even `execute`.

**Comment by tiagogsc** [comment]
At the first glance it sounds a good to do everything or almost in the
sequence randomise, rebuild, communicate, execute, synchronise.

Em Qua, 14 de set de 2016 15:13, Pedro R. Andrade <notifications@github.com>
escreveu:

**Comment by tiagogsc** [comment]
Idea

Em Qua, 14 de set de 2016 15:20, Tiago Garcia de Senna Carneiro <
tiagogsc@gmail.com> escreveu:
