### ISSUE TITLE
Add error message when trying to create a Map with invalid file.

### ISSUE THREAD

**Issue by JoaoVitor123** [TerraME/terrame#1431]
Add error message when trying to create a CellularSpace with an invalid file.
When trying to created a Map with "farms.shp" file, not show the error, but not possible to create a Map with this file.

**Comment by JoaoVitor123** [comment]
[farms_shp.zip](https://github.com/TerraME/terrame/files/487308/farms_shp.zip)

**Comment by avancinirodrigo** [comment]
> Add error message when trying to create a CellularSpace with an invalid file. 

Add error message when trying to create a CellularSpace with a **file that is not a really Cellular Space.**

**Comment by pedro-andrade-inpe** [comment]
The point here is that it is only possible to create a `Map` from a `virtual` `CellularSpace`, which is not the case of a shapefile. I will check this in `Map` to stop with an error (instead of showing nothing).
