### ISSUE TITLE
terrame -strict script.lua

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1460]
When one executes a given script in strict mode, TerraME must execute luacheck with this script, showing warnings as below:

```
"Warning:  "..luacheck.get_message(issue)..". In file "..<file>..", line "..<line>,,"."
```

- Only warnings should be shown (fatal and errors should be avoided)
- If running in -debug mode, it should stop with error
- It must convert the first character of the error message to upper case
- Implement two execution tests with a simple script, one with debug and strict modes

**Comment by pedro-andrade-inpe** [comment]
#1412

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe,

>  Implement two execution tests with a simple script, one with debug and strict modes

How do I do this?

**Comment by pedro-andrade-inpe** [comment]
In `terrame/test`, implement a script and save it within `scripts` and then update `commands.lua` to execute such script.
