### ISSUE TITLE
terrame -package pkg -check

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1461]
Run luacheck for a given package when executing `-check`. The following verifications must be executed:

- For a given package, it should verify pkg/lua and pkg/tests (recursively)
- For base package, it should also verify src/lua to help us verifying these files
- warnings, errors, and fatal must be shown, using the same string described in #1460 (note that it should not show the complete path of the file, only `tests/mytest.lua`, for instance). Note that it should not stop when an error is found.
- in the end, `os.exit` must return the number of errors found, for the CI server.
- Add an execution test for this, with a new package called `check`.
- Document this in `-help`.

**Comment by pedro-andrade-inpe** [comment]
#1412

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe,
Is there a function that returns the file list of a directory and its subdirectories?

**Comment by pedro-andrade-inpe** [comment]
No, but there is a similar function called testdirectories(directory, ut) in `src/lua/test.lua`.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe,

> For base package, it should also verify src/lua to help us verifying these files

Is there a function to get src path?

**Comment by pedro-andrade-inpe** [comment]
`sessionInfo().path.."/lua"`?

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe,

> Add an execution test for this, with a new package called check.

 Luacheck is not a package, do I must create a package for test?

**Comment by pedro-andrade-inpe** [comment]
Yes, the package should be located in `test/packages`, such as `test/packages/check`. Note that this package should not contain luacheck code, but it is a package that has some errors that must be found by `terrame -check`.
