### ISSUE TITLE
Layer:simplify()

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1484]
Implement a function that takes a threshold as argument to simplify a layer of polygons or lines. Use TerraLib functionalities to do that.

**Comment by pedro-andrade-inpe** [comment]
It must have additional parameters to indicate where to save the output. Think if it would be interesting to add this functionality as an additional parameter to `Layer:export()`.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, like this Extent?
```xml
<te_map:DataSetLayer id="66a539fc-29ad-4dc9-9c5a-8ded93908478">
    <te_map:Title>Setores</te_map:Title>
    <te_map:Visible>NOT_VISIBLE</te_map:Visible>
    <te_map:Encoding>LATIN1</te_map:Encoding>
    <te_map:DataSetName>Setores_Censitarios_2000_pol</te_map:DataSetName>
    <te_map:DataSourceId>7470ac20-69ee-44b9-a5cc-c2ab3869217a</te_map:DataSourceId>
    <te_map:SRID>29191</te_map:SRID>
    <te_map:Extent llx="547177.3501989994" lly="9485214.1871199999" urx="700365.9054510002"   ury="9583948.6234280355"/>
    <te_map:RendererId>ABSTRACT_LAYER_RENDERER</te_map:RendererId>
    <te_map:CompositionMode>0</te_map:CompositionMode>
</te_map:DataSetLayer>
```

**Comment by pedro-andrade-inpe** [comment]
This issue is to provide a function called `Layer:simplify` to execute an algorithm such as https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm (check if it is implemented in TerraLib). It should produce another layer with the output.

**Comment by avancinirodrigo** [comment]
By now, terralib system handle lines only.
The polygon support is being planned to developing by terralib team as soon as possible.
The contact is Ruan.

**Comment by pedro-andrade-inpe** [comment]
This issue was solved by https://github.com/TerraME/terrame/pull/1762/commits/4b870b4cf80a1d9181450e8a1ed496ec2c9460c2
