### ISSUE TITLE
Error when execute terrame within /bin came back on Windows

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1501]
The message that alert the user is not showing.
Type some command within /bin for reproduce.

It was not verified in other OS.

**Comment by avancinirodrigo** [comment]
It can be associated to #1500

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, please test this as https://github.com/TerraME/terrame/pull/1489 was already closed.

**Comment by avancinirodrigo** [comment]
It didn't work.
