### ISSUE TITLE
Automatic installer for windows

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1507]
Create an automatic installer for Windows in the CI server.

**Comment by avancinirodrigo** [comment]
As #1508.
It needs a research to find how execute cpack by command line in windows. 
I think that is as linux and mac as.

**Comment by pedro-andrade-inpe** [comment]
This is already working properly!

**Comment by avancinirodrigo** [comment]
The proccess is not correct, review the steps in #1509.

**Comment by hguerra** [comment]
Installer does not have doc.

```sh
PANIC: unprotected error in call to Lua API (Error: Directory 'C:/TerraME/bin/packages/base/doc/' does not exist.)
```

**Comment by hguerra** [comment]
Problems were found with `Install package` in the graphical interface

```sh
Downloading package 'sysdyn'
Error executing lua slot: "Error: Package 'sysdyn' is not installed."
```

**Comment by hguerra** [comment]
Problems were found with `Install local package` in the graphical interface

```sh
Error: Package 'ca' is not installed
```

**Comment by pedro-andrade-inpe** [comment]
Windows installer is ok! Nice job @raphaelrpl and @avancinirodrigo!!
