### ISSUE TITLE
Automatic installer for Mac

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1508]
Create an automatic installer for Mac in the CI server.

**Comment by avancinirodrigo** [comment]
As #1509 but turn ON TERRAME_BUILD_AS_BUNDLE and TERRAME_CREATE_INSTALLER.

**Comment by avancinirodrigo** [comment]
@raphaelrpl, 
Check cpack command, it uses "DragNDrop" generator.
http://www.dpi.inpe.br/jenkins/job/terrame-installer-mac-el-captain/lastBuild/consoleFull

**Comment by pedro-andrade-inpe** [comment]
Mac installer is not running terrame:

```
[pedro@/Applications] $ terrame
PANIC: unprotected error in call to Lua API (error loading module 'qtluae' from file '/Applications/terrame.app/Contents/lib/qtluae.dylib':
	dlopen(/Applications/terrame.app/Contents/lib/qtluae.dylib, 6): Symbol not found: _lua_remove
  Referenced from: /Applications/terrame.app/Contents/lib/libqtlua.dylib
  Expected in: /Applications/terrame.app/Contents/lib/liblua.dylib
 in /Applications/terrame.app/Contents/lib/libqtlua.dylib)
/Applications/terrame.app/Contents/bin/terrame: line 11:  2540 Abort trap: 6           "$TME_PATH"/terrame $@
```
@avancinirodrigo

**Comment by avancinirodrigo** [comment]
It seems to me that is problem in qt version, because the libs qtlua and qtluae were compiled in another one.
@raphaelrpl,
See in https://github.com/TerraME/terrame/wiki/Building-and-Configuring which version must be used to the libs. This problem can be impacting in the other installer.

**Comment by pedro-andrade-inpe** [comment]
@raphaelrpl, it is important to tell you that this kind of error cannot be captured in the CI tests as it is related to the graphical interface of TerraME.

**Comment by pedro-andrade-inpe** [comment]
Mac installer is working properly! Very nice, @raphaelrpl and @avancinirodrigo!!!
