### ISSUE TITLE
CellularSpace:save - order of new columns

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1565]
CellularSpace:save creates new columns apparently using `forEachElement`, which makes columns in different order each time it is saved. Keep the original columns in the same order, and add the new ones alphabetically.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, alphabetically is better but not good enough, for luccme is better to keep the order always because the huge number of variables. Ensure insertion order facilitates the analysis.
