### ISSUE TITLE
consistency in Layer:fill with coverage

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1567]
`Layer:fill` with `coverage` returns values from 0 to 1 with polygons and from 0 to 100 with raster data. Update raster to return from 0 to 1 as well.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, it is internal from terralib.

**Comment by avancinirodrigo** [comment]
Waiting solution from Felipe terralib team.
