### ISSUE TITLE
Review command associated to the libs 'libicu*' in CMakeLists on Linux

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1573]
Review if the libicu* is necessary to TerraME.
Firstly, remove the command.
If it does not work, review one by one.

Associated to #1509.

**Comment by pedro-andrade-inpe** [comment]
This issue should be closed by https://github.com/raphaelrpl/terrame/commit/7574e06ba84d59e77c671649bda05bc14712db63
