### ISSUE TITLE
User must select template postgis to create new database

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1581]
According terralib team (felipe), now the user must select some template with postgis extension.
There was not this problem in release-5.1.

**Comment by pedro-andrade-inpe** [comment]
Can you explain this? Will the user need to set a new argument?

**Comment by avancinirodrigo** [comment]
Yes, a new parameter of connection.
As
``` 
template = "template0"
```

**Comment by avancinirodrigo** [comment]
TerraLib fixed it.
