### ISSUE TITLE
clean visual arrangement when a new file is set

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1618]
When one executes two examples in the graphical interface, the second example inherits the visual arrangement of the first because TerraME does not clean the visual arrangement.  See below how it is implemented in `src/lua/terrame.lua`.
```lua
    local cObj = TeVisualArrangement()
    cObj:setFile(displayFile)

    if _Gtme.File(displayFile):exists() then
        local display = dofile(displayFile)

        _Gtme.forEachElement(display, function(idx, data)
            cObj:addPosition(idx, data.x, data.y)
            cObj:addSize(idx, data.width, data.height)
        end)
    end
```

Clean it in the C++ code in `setFile` function.

**Comment by avancinirodrigo** [comment]
It was implemented, but is not possible to test because #1641.
