### ISSUE TITLE
Coverage operation from raster is not renaming the created attribute

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1640]
Use this operation for reproduce, eg.:
```lua
cs:fill{
	operation = "coverage",
	layer = fert.name,
	attribute = "fert",
	select = "OBJECTID"
}
```

The attribute created should be named `fert_[OBJECTID-value]`, but it is named ` OBJECTID_[OBJECTID-value]`.

**Comment by pedro-andrade-inpe** [comment]
Coverage operation from vector is not renaming as well. I will link a commit to this issue indicating a new test that needs to be updated to solve this issue.
