### ISSUE TITLE
tables with special characters in PostGis

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1658]
When a shapefile has special characters in its name and one tries to create a cellular layer, it stops with an error such as:

```
Error:Could not execute the sql statement due to the following error: ERROR:  syntax error at or near "-"
LINE 1: CREATE TABLE public.itaituba-census()
```

Some tests will be skipped and need to be rolled back to solve this issue.

**Comment by pedro-andrade-inpe** [comment]
See also https://github.com/TerraME/terrame/pull/1645/commits/b4a6cf0309f62af09ea68b8da4c7605ca960423c

**Comment by avancinirodrigo** [comment]
Investigate `ds->isPropertyNameValid(name);` in terralib.
