### ISSUE TITLE
creating cells with latlong projection

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1670]
Creating a cellular layer with latlong projection produces wrong outcome such as the one below. see the core to reproduce it in the bottom of this comment.

![screen shot 2017-02-07 at 14 14 11](https://cloud.githubusercontent.com/assets/8777631/22699959/1bb4e61a-ed40-11e6-8f93-3e9a6632c44e.png)

```lua
import("terralib")

p = Project{
    file = "mg.tview",
    clean = true,
    cities = filePath("test/MG_cities.shp", "terralib")
}


cl = Layer{
    project = p,
    resolution = 0.1,
    clean = true,
    file = "mg.shp",
    name = "cells",
    input = "cities"
}
```

Projection: MODIS custom spheroid', with SRID: 100001.0 (PROJ4: '+proj=longlat +lon_0=0 +a=6371007.181 +b=6371007.181 +no_defs '

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, can you try to do this in TerraView, please?

**Comment by avancinirodrigo** [comment]
It has been tested in all OS and TerraView, this problem did not happen. Maybe, this error was associated to #1667.
Anyway, there are many tests that create cellular space and test the number of cells created. Like that in `functional/basic/Layer`:
```lua
		clName1 = "Sampa_Cells"
		local l1 = Layer{
			project = proj,
			input = layerName1,
			name = clName1,
			resolution = 0.7,
			file = filePath1
		}

		-- BOX TEST
		local tl = TerraLib{}
		local clSet = tl:getDataSet(proj, clName1)
		unitTest:assertEquals(getn(clSet), 68)

		clName1 = clName1.."_Box"
		local filePath4 = clName1..".shp"

		File(filePath4):deleteIfExists()

		Layer{
			project = proj,
			input = layerName1,
			name = clName1,
			resolution = 0.7,
			box = true,
			file = filePath4
		}

		clSet = tl:getDataSet(proj, clName1)
		unitTest:assertEquals(getn(clSet), 104)
```

**Comment by pedro-andrade-inpe** [comment]
This problem is not occurring anymore.
