### ISSUE TITLE
Problem with 'coverage' operation when the selected attribute has 10 characters from shapefile

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1686]
When is used a selected attribute that has 10 characters (or maybe a little less), the output name do not follow a pattern. Probably, because the constraint of 10 characters in the name of attributes on shapefiles.

Use the data for reproduce:
`test/BCIM_Unidade_Protecao_IntegralPolygon_PA_polyc_pol.shp`
and
`test/limitePA_polyc_pol.shp`

**Comment by pedro-andrade-inpe** [comment]
I think we should read the data to verify the larger attribute value. If its size plus the attribute name is larger than 10, it should stop with an error or at least show a warning.
