### ISSUE TITLE
Graphics are overlaying on Linux

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1741]
Run something that has more than one graphic for reproduce.

**Comment by pedro-andrade-inpe** [comment]
In Gnome, as there is a sidebar on the left with icons, the maps that would be placed within such are are being automatically moved to the right. See how can it be automatically recognised and move all observers to the right automatically.

There is also another point that the title bar of the observers have different sizes in different operational systems, which makes the observer size different. save and load the sizes of the whole window. It seems that it is saving and loading the canvas area instead.
