### ISSUE TITLE
Images for data files Documentation

### ISSUE THREAD

**Issue by rvmaretto** [TerraME/terrame#176]
TerraME should allow the users to insert images of the data, e. g., maps or temporal series. A possible solution is to make TerraME to generate these images automatically through the Observer, or to allow the user to put these images inside package/data or package/images.

**Comment by pedro-andrade-inpe** [comment]
Use folder snapshots, with the first plot of the observer just after loading the data.

**Comment by pedro-andrade-inpe** [comment]
Add an aditional parameter to `data{}`, called `map`, that get parameters to be used by `Map`.
