### ISSUE TITLE
Error in '-doc' after change Layer:attributes()

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1766]
Something was broken after change Layer:attributes() #1690.
It was not possible identify where is the error:
```
Building documentation for package 'terralib'
Loading package 'terralib'
Parsing 'data.lua'
Processing lua files
Processing 'amazonia-postgis.lua'
Processing 'amazonia.lua'
Processing 'cabecadeboi.lua'
Processing 'emas.lua'
Processing 'itaituba.lua'
Checking directory 'data'
Checking properties of data files
Processing 'amazonia-indigenous.shp'
Error: Argument '#1' is mandatory.
```

**Comment by avancinirodrigo** [comment]
The error was fixed, but there are two problems yet, the `doc.lua` is difficult to debug, because it doesn't show error line number and it seems to me that `-doc` executes `-version` when there is a error, this causes a problem in Jenkins:
http://www.dpi.inpe.br/jenkins/job/terrame-ci-doc-base-linux-ubuntu-14.04/641//consoleFull

**Comment by pedro-andrade-inpe** [comment]
This issue was solved by https://github.com/TerraME/terrame/pull/1769/commits/2760780ccb5ea13faa2d63cccade43746173f16f
