### ISSUE TITLE
Operator area (fill function) returning NULL rc1

### ISSUE THREAD

**Issue by vilmount** [TerraME/terrame#1775]
The operator area on fill function become to return NULL again not 0 in rc1 version.

**Comment by pedro-andrade-inpe** [comment]
@vilmount could you please attach the data and the script you used to reproduce the problem?

**Comment by vilmount** [comment]
`--------------------------------------------------------------
--          This file contains a Fill Cell Script           --
--               Compatible with LuccME 3.0                 --
--       Generated with Fill Cell Script Configurator       --
--               17/04/2017 at 11:00:02                     --
--------------------------------------------------------------

local x = os.clock()
import("terralib")

-- CREATING PROJECT --
print("Creating Project")
proj = Project {
	file = "t3mp.tview",
	clean = true
}

-- ADDING LAYERS --
print("Adding Layers to the Project")
l1 = Layer{
	project = proj,
	name = "limit",
	file = "C:\\Treinamento\\preenchimentoDeCelulas\\limitePA_src29101_pol.shp"
}

print("Limit added")
l2 = Layer{
	project = proj,
	name = "layer2",
	file = "C:\\Treinamento\\preenchimentoDeCelulas\\rodoviasPA_src29101_lin.shp"
}
print("Layer2 added")

l3 = Layer{
	project = proj,
	name = "layer3",
	file = "C:\\Treinamento\\preenchimentoDeCelulas\\areasProtegidasPA_src29101_pol.shp"
}
print("Layer3 added")

l4 = Layer{
	project = proj,
	name = "layer4",
	file = "C:\\Treinamento\\preenchimentoDeCelulas\\areasProtegidasPA_src29101_pol.shp"
}
print("Layer4 added")

l5 = Layer{
	project = proj,
	name = "layer5",
	file = "C:\\Treinamento\\preenchimentoDeCelulas\\areasProtegidasPA_src29101_pol.shp"
}
print("Layer5 added")

-- CREATING CELLULAR SPACE --
print("Creating Cellular Space")
local cs = Layer{
	project = proj,
	source = "shp",
	name = "cs",
	input = l1.name,
	resolution = 50000,
	file = "csInterno.shp",
	clean = true
}

-- ATTRIBUTES TO FILL --
print("Filling Attribute in Layer2")
cs:fill{
	layer = "layer2",
	operation = "distance",
	attribute = "dist_rodo",
}

print("Filling Attribute in Layer3")
cs:fill{
	layer = "layer3",
	operation = "area",
	attribute = "area_UC",
}

print("Filling Attribute in Layer4")
cs:fill{
	layer = "layer4",
	operation = "presence",
	attribute = "pres_UC",
}

print("Filling Attribute in Layer5")
cs:fill{
	layer = "layer5",
	operation = "distance",
	attribute = "dist_UC",
}

print(string.format("\nElapsed time : %.2fs\n", os.clock() - x))
print("\nEnd of Script")

`

**Comment by avancinirodrigo** [comment]
The problem seems to be associated with the default value which it is not used in 'area' operation.
