### ISSUE TITLE
count operation of fill function has null values

### ISSUE THREAD

**Issue by vilmount** [TerraME/terrame#1829]
The default value for the count operation is null, not 0.

`cs:fill{
	layer = "teste",
	operation = "count",
	attribute = "rodcount"
}`

**Comment by pedro-andrade-inpe** [comment]
Strange. The test for windows looks fine: https://github.com/TerraME/terrame/blob/master/packages/terralib/log/windows/lines-count.png

@vilmount, can you provide a script and data to reproduce such problem?

**Comment by vilmount** [comment]
My result
![image](https://cloud.githubusercontent.com/assets/17905647/26168761/a4fbb4f2-3b11-11e7-9ece-552612715686.png)

**Comment by pedro-andrade-inpe** [comment]
The script creates attribute "rodcount", while the image has attribute "apcount". Anyway, I need script and data in order to reproduce such problem.

**Comment by avancinirodrigo** [comment]
It seems associated to `default` argument.

**Comment by avancinirodrigo** [comment]
There is no `default` for `count`.

**Comment by pedro-andrade-inpe** [comment]
You are right:

```lua
            count = function()
                if belong(repr, {"point", "line", "polygon", "surface"}) then
                    verifyUnnecessaryArguments(data, {"attribute", "layer", "operation"})
                    data.select = "FID"
                else
                    customError("The operation '"..data.operation.."' is not available for layers with "..repr.." data.") -- SKIP
                end
            end,
```

Just set the default value of `default` to zero and check the images in the log directory. The only strange point is why it is shown as zero in the logs.

This issue might be related to #1784 (although the other one is a PostGIS problem).

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe,
I guess that there is another problema here beyond the `default`. 
The `count` operation creates a data with null values, but `Map` is coloring as `0`.
test/shapefile/Layer.lua
```lua
		clamaz:fill{
			operation = "count",
			layer = portos,
			attribute = "pointcount"
		}

		cs = CellularSpace{
			project = proj,
			layer = clamaz.name
		}

		map = Map{
			target = cs,
			select = "pointcount",
			value = {0, 1, 2},
			color = {"green", "red", "blue"}
		}
```

**Comment by pedro-andrade-inpe** [comment]
When a cellularspace is loaded, how null values are read?

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe 
Currently, terralib returns the value as `0`, but it is possible check if the value is null, however, if sets a value as `nil` in a table, the key is removed.  
What would be the solution for it?

**Comment by pedro-andrade-inpe** [comment]
Solved by https://github.com/TerraME/terrame/pull/1835/commits/073a8762788e6a2eabb261253f7c0b381120f06a.
