### ISSUE TITLE
add TerraLib 5.0 as a TerraME package

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#186]
TerraLib will be available as a Lua library. Encapsulate this as a TerraME package.

**Comment by pedro-andrade-inpe** [comment]
Break this into a set of tickets to update:
- Load functions: CellularSpace(), Society(), CellularSpace:loadNeighborhood(), Environment:loadNeighborhood()
- Save function: CellularSpace:save(). Perhaps add Society:save()
- fill cell functions

**Comment by avancinirodrigo** [comment]
TerraLib is a package now, but the functions are to fillcell and CellularSpace, it not to users, although they can use.
