### ISSUE TITLE
Research about how to solve conflict with libs in Linux

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1868]
There is a problem when exist a lib with the same name than some system lib.
I think that it is a recurring problem on Linux.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, try this:

If you want to avoid LD_LIBRARY_PATH, you can also do this, during linking:

gcc -o exename -L/path/to/dynamiclib/ -lnameofLib \
    -Wl,-R/path/to/dynamiclib/ sourceCode1.c ...
The -Wl,... is used to pass extra commands to the linker, and in this case, with -R you tell the linker to store this path as the "default search path" for the .so.

From https://superuser.com/questions/192573/how-do-you-specify-the-location-of-libraries-to-a-binary-linux

**Comment by avancinirodrigo** [comment]
Remove LD_LIBRARY_PATH from jenkins and instructions.

**Comment by avancinirodrigo** [comment]
The solution works just in libs that link in executable terrame. Libs that are used only in lua layer still need be added in lua cpath.
