### ISSUE TITLE
Error when Zerobrane does not find the TME_PATH on Linux

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1883]
When zerobrane doesn't find tme_path, it is setting the mac path and, as result, the system doesn't work.

**Comment by pedro-andrade-inpe** [comment]
The following file works for Mac. Please check in Windows and Linux. It is placed in `terrame/ide/zerobrane/terrame.lua`

[terrame.zip](https://github.com/TerraME/terrame/files/1098784/terrame.zip)
