### ISSUE TITLE
grid=true and last line/column

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1890]
When using grid=true, the last line and column do not have a black line. Fix it.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, please check `src/observer/components/painter/painterThread.cpp`. I think both fors below should be `<=` instead of `<`.

```C++
void PainterThread::drawGrid(QImage &imgResult, double &width, double &height)
{
    mutex.lock();

    QPainter p(&imgResult);
    p.setPen(QPen(Qt::black));

    for (int j = 0; j < imgResult.height(); j++)
    {
        for (int i = 0; i < imgResult.width(); i++)
        {
            p.drawRect(QRectF(i * width, j * height, width, height));
        }
    }

    mutex.unlock();
}
```

**Comment by avancinirodrigo** [comment]
Actually, the problem is associated with the accuracy of the float, in which it was necessary to adjust the borders.
