### ISSUE TITLE
Review jenkins documentation for job and scripts creation 

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1894]
For this task is necessary create a new package #1815, and with this, it is possible to check the documentation for job and scripts creation.

**Comment by avancinirodrigo** [comment]
This resolves #1837.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, package `logo` will be renamed to `abm`. I think this can be a nice test for this issue.

**Comment by pedro-andrade-inpe** [comment]
Closed by https://github.com/TerraME/terrame/pull/1884
