### ISSUE TITLE
Add command checker in jenkins scripts

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1896]
There are some commands that must be executed in jenkins scripts to ensure the correct configuration and its execution.
It can be made by the command bellow after some command in the script:
```bash
valid $?
```

**Comment by pedro-andrade-inpe** [comment]
It should be closed by https://github.com/TerraME/terrame/pull/1977/commits/a35dc21e9466057e979386975026ccaa46b7d621.
