### ISSUE TITLE
bug running with wrong projection

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1913]
Update `amazonia.lua` and remove the `epsg` of the only tif file. A warning is correctly shown, but TerraME aborts. Fix it.

**Comment by avancinirodrigo** [comment]
This warning was changed to error.
See in: https://github.com/TerraME/terrame/pull/1903/commits/a8e17966259064e0db872d08bc0bf5354cf5fca7

**Comment by pedro-andrade-inpe** [comment]
Good!
