### ISSUE TITLE
URI and space in the file path in tview files

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1916]
When reading a tview file where there is a space in the path, TerraLib does not convert the value to space. For example, the URI below:

```xml
<te_da:URI>file%3A%2F%2F%2FUsers%2Fpedro%2Fa%2520b%2Famazonia.shp</te_da:URI>
```

is converted to 

```
/Users/pedro/a%20b/
```

It should be 

```
/Users/pedro/a b/
```

**Comment by avancinirodrigo** [comment]
This error seems in terralib decoder.
You can to reproduce in the terraview.
