### ISSUE TITLE
Error with projection in Project basic test on Mac

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1934]
See in:
http://www.dpi.inpe.br/jenkins/job/terrame-unittest-gis-mac-el-captain/294/console

Run `project` basic test to reproduce.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, the link above is the `lastBuild`, therefore it was already updated.

**Comment by avancinirodrigo** [comment]
This error was sent to terralib team.
