### ISSUE TITLE
 Layer:fill coverage has output greater than one

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1968]
Layer:fill coverage has output greater than one. It should be at most one. See the output of a test to be linked to this issue.

**Comment by pedro-andrade-inpe** [comment]
Implement an optional argument `union = false` to `Layer:fill` with strategy `coverage`. When `true`, this operation should compute the union of all polygons within the cell before computing the area, in order to guarantee that the attribute values will be at most one.

**Comment by pedro-andrade-inpe** [comment]
Possibly this should be another strategy for fillAttribute in TerraLib, as the strategies do not get extra arguments. Please @avancinirodrigo, talk to them about this issue.

**Comment by avancinirodrigo** [comment]
According to Marisa (TerraLib), this has been resolved.

**Comment by pedro-andrade-inpe** [comment]
Rolling back the title, as TerraLib does not implement the other solution.

**Comment by pedro-andrade-inpe** [comment]
There was a confusion in the description of this issue. There are two problems, the other one is now in #2009.
