### ISSUE TITLE
Layer:box()

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1984]
Implement `Layer:box()` to make easier to the user to access the bounding box of a Layer.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, what is the return format?

**Comment by pedro-andrade-inpe** [comment]
A table:

```lua
{
    xMin = ...,
    xMax = ...,
    yMin = ...,
    yMax = ...
}
```
