### ISSUE TITLE
Confuse error message in Map select attribute 

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#2015]
To reproduce:

Create a script like this below and set `select` with a attribute which it there isn't in shapefile.
```lua
local cs = CellularSpace{

	file = "cs2.shp"

}

local map = Map{

	target = cs,

	select = "distance",

	slices = 10,

	color = "Blues"

}
```
```bash
Error: Argument '#1' is mandatory.
Stack traceback:
    File 'show.lua', line 5, in call to function 'Map'
```

**It would be interesting to check the selected attribute.**

**Comment by pedro-andrade-inpe** [comment]
Attribute `distance` exists in the `CellularSpace`. It is a function that requires a `Cell` as argument, but it is called without any argument because the selected function is assumed not to have any argument. I will replace this error by

```
Error: Could not execute selected function 'distance' properly.
```

**Comment by avancinirodrigo** [comment]
Still confusing, because "distance" is a string value, not a key.
 Why does CS handle it like function?

**Comment by pedro-andrade-inpe** [comment]
`cell.distance` does exist. So if you try to observe it (what the code above does) then it will call this function and get the result for each cell. However this function requires an argument and then the error above is shown.

**Comment by avancinirodrigo** [comment]
I see, but it is still confuse to the user, the message doesn't help so much.  
This helps:
```
Error: Selected element 'attr' does not belong to the target.
```

**Comment by pedro-andrade-inpe** [comment]
That's the point. It does belong to the target!!

**Comment by avancinirodrigo** [comment]
You are a advanced user, so this message doesn't help for dummies:
```
Error: Could not execute selected function 'distance' properly.
```

**Comment by pedro-andrade-inpe** [comment]
What about:

```
Selected attribute 'distance' is a function. It did not execute properly when called without arguments.
```

**Comment by avancinirodrigo** [comment]
The problem is that, Map shouldn't matter if there is a function named 'distance' in the Cell. That seems a strange association between Map and Cell.
There is another problem, 'distance' is a common name to be used in some data as well as 'area' or 'sample' and so on.
The confusing is on here:
Selected attribute 'distance' is a function.. That is not true, 'distance' is a Cell function and not a Map one.

**Comment by pedro-andrade-inpe** [comment]
You are deviating from the topic. Maps observe attributes of Cells. In order to avoid having attributes that need to be updated explicitly just to be observed by Maps, we allowed Maps to observe functions from Cells that return the observed values. See the example below:

https://github.com/TerraME/terrame/blob/master/packages/base/examples/barros.lua

**Comment by avancinirodrigo** [comment]
I'm trying to understand the message suggested by the system.
What should I do if there is an attribute in Cell that it has the same name of a function? 
I think the message should answer this question. That helps the user.

**Comment by pedro-andrade-inpe** [comment]
The function (e.g. "distance") will be replaced by the attribute and a warning will be shown. In this case, the user can select the attribute ("distance"), and the error above will not occur.
