### ISSUE TITLE
Problem with blank space in directory path on Project

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#2019]
It seems that the project is not decoding the path. It needs review.

Reported from user:
![2017-09-25](https://user-images.githubusercontent.com/7737803/30915768-2c2dc2c0-a36e-11e7-9b8f-2a3be44e18a2.png)

**Comment by pedro-andrade-inpe** [comment]
This issue is related to #1918.

**Comment by pedro-andrade-inpe** [comment]
Shouldn't this issue be solved by #1916?

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, to close this issue as well as #1918, just verify if there is some space or special character in the path of a project or layer (when dealing with files) and stop with an error when instantiating them.

**Comment by avancinirodrigo** [comment]
Associated with #659.

**Comment by avancinirodrigo** [comment]
Characters mapping:
https://en.wikipedia.org/wiki/List_of_Unicode_characters
