### ISSUE TITLE
Error when doc directory doesn't exist in some package

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#2071]
When doc directory doesn't exist a error is shown:
```
Error executing lua slot: "Error: Directory '/home/developer/terrame/build-cmake/install/bin/packages/publish/doc/' does not exist." 
```
It would be better if the system showed how run `-doc`.
Note: this error has happened in Linux.

**Comment by pedro-andrade-inpe** [comment]
How can I reproduce this error?

**Comment by avancinirodrigo** [comment]
Either remove doc directory or download a package directly, after that, select the package in GUI.

**Comment by wsenafranca** [comment]
What is the expected behavior? Should I disable "Documentation" button and show a warning message saying to run -doc?
