### ISSUE TITLE
Ubuntu 18 jenkins environment

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#2118]
Create Ubuntu 18 environment in Jenkins, it isn't necessary to create the jobs.
Update the environment creation process at Wiki.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, can I close this issue?

**Comment by avancinirodrigo** [comment]
You can't, the environment include all job scripts.

**Comment by pedro-andrade-inpe** [comment]
So this issue should be yours, isn't it?
