### ISSUE TITLE
ZeroBrane commands is running only in base on Mac

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#2142]
For reproduce.
Copy a package in somewhere, open the package `description.lua` in zerobrane and execute some `Project` command.

**Comment by pedro-andrade-inpe** [comment]
This problem might be related to local packages, possibly causing the same error in other operational systems.

**Comment by pedro-andrade-inpe** [comment]
I executed test, doc, check in Mac and they worked properly. The visual tests were updated so if this errors occurs again or in other operational system the problem will be detected.
