### ISSUE TITLE
Problem reading line data

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#2143]
There is a problem reading the following shapefile storing lines: [roads.zip](https://github.com/TerraME/terrame/files/1674745/roads.zip). The source code below

```lua

cs = CellularSpace{
    file = "ParaRodovias2.shp",
    missing = 0
}

print(#cs)
```

gets the following error:

```
Error: attempt to index a number value (local 'geom')
Stack traceback:
    File 'cs.lua', line 2, in call to function 'CellularSpace'
```

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe 
There are 287 lines in that data, but only 43 firsts has geometry. 
Therefore, the problem is in the data and it can be treated.

**Comment by pedro-andrade-inpe** [comment]
Yes, just stop with an error.

**Comment by avancinirodrigo** [comment]
The Gis system can open this file and maybe that data might be used for other purpose. 
Error or warning?

**Comment by pedro-andrade-inpe** [comment]
In this case, it is better to stop with an error to allow the user to fix the data before loading it in TerraME.
