### ISSUE TITLE
UnitTest:assert() with functions

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#2153]
Allow `UnitTest:assert()` to get functions as argument. In this case, the test will execute the function and should not have any error. If there is some error in the asserts, the traceback should recognize the name of the test function (in the case below, `count`), and show it. Check if `assert` is a good name, once it should get a non-{`nil`, `false`} value as argument. 
```lua
        local function count()
            local missCount = 0
            forEachCell(cs, function(c)
                if c.pointcount == -1 then
                    missCount = missCount + 1
                end
            end)

            unitTest:assertEquals(missCount, 156)
        end

        count()

        unitTest:assert(count) -- check if it is a good name
```

**Comment by avancinirodrigo** [comment]
Add the possibility of SKIP all asserts in the function.
