### ISSUE TITLE
Investigate io.write() for tests

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#2158]
The solution here https://github.com/TerraME/gpm/issues/79 uses io.write() and io.flush() functions. For finalize the "writes" is used a print() that overwrite the last write, but in testing, the print() is overwrote, this is causing a problem.
See  the problem in GPM example tests.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, I will replace `io.write()` by `print()` during tests, ok?

**Comment by avancinirodrigo** [comment]
I think this issue became invalid, see the solution in: https://github.com/TerraME/gpm/pull/86/commits/6934828668ad9f1ee104944dfb02798574f6ff51
