### ISSUE TITLE
Problem with skip looking for lines of source code

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#2178]
On the command: `terrame -test`.
Even when `lines` is equals `false` this function is being executed: `Skip looking for lines of source code`
Besides, this function is too slow on Windows.
Could this function disabled when it is being executed with `lines == false`?

**Comment by pedro-andrade-inpe** [comment]
It's true. The line
```lua
debug.sethook(trace, "l")
```
is executed everytime, but now everything related to it is unnecessary when `lines = false`.
