### ISSUE TITLE
Test projects with QGIS 3.0

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#2204]
Check if the current implementation to read qgs files still works.

**Comment by avancinirodrigo** [comment]
Current works with previous version, you might convert to that, but version 3 generates a different qgs that it is not compatible with previous version.

**Comment by avancinirodrigo** [comment]
Related to #1947

**Comment by pedro-andrade-inpe** [comment]
Closed by https://github.com/TerraME/terrame/pull/2259
