### ISSUE TITLE
Bug in distance to polygons

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#2237]
The distance to polygons strategy does not compute the distance to the Cell's centroid. It computes the shortest distance to any part of the cell. Moreover, when there is an overlap, it uses missing as the returning value, which stops the algorithm with an error as it needs to read the data again. Fix it.

**Comment by avancinirodrigo** [comment]
In fact, there is no option about centroid or another spatial relation to filling a vector to vector attribute.  
It can be seen on Attribute Fill GUI in TerraView.

The missing problem was solved, See in the commit below.
