### ISSUE TITLE
Window button in Map does not work

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#2267]
In a Map, the "Window" button does not work. Just remove the button "Restore" and replace the "Window" behavior to the one in "Restore".

**Comment by avancinirodrigo** [comment]
It was created a group box for zoom which improved the usability.
See below.
![map_zoom](https://user-images.githubusercontent.com/7737803/51746604-db1b7c80-208d-11e9-902d-41cad8066c95.png)

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe 
Now, this issue seems associated with an enhancement instead of a bug.
