### ISSUE TITLE
Improving Layer:fill message

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#2282]
`Layer:fill` currently shows the following message:

```
Processing 'coverage' operation 98%
```

It would be interesting to show the name of the attribute being created in addition to the operation, because the user can select the same operation several times.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe 
Could you please give the message?

**Comment by pedro-andrade-inpe** [comment]
Creating attribute 'cov_' using operation 'coverage' 98%
