### ISSUE TITLE
Overwrite geojson stops to work

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#2322]
Overwrite geojson stops to work after update terralib.
It seems that the problem is related to gdal updating.
The error is caused by a new attribute within geojson file called `name` that holds the dataset name.

Associated with #2323

**Comment by abitrolly** [comment]
Are there any regression tests for that functionality?

**Comment by avancinirodrigo** [comment]
Hi @abitrolly, you can see here -> https://github.com/avancinirodrigo/terrame/commit/e4d1cc4a7e0196ae85a08b0a2237b760975c13bc that the test is commented for a specific function.
And here -> https://github.com/avancinirodrigo/terrame/commit/92e02102a9bf639b0e1d75a07c3ac45cd8c7b0e0 there is a solution for another function to hacks this problem that consisting in save the geojson in a temporary file, then delete the original, and finally, recreating the geojson with the correct name. It is not the best solution, but it works for us.
