### ISSUE TITLE
Problem running in directories with space in Mac

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#2351]
TerraME does not run scripts that belong to a directory with space in Mac. It is strange because it runs in other operational systems.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, please fix this to the next version.

**Comment by avancinirodrigo** [comment]
That is really strange. There are tests for blank space for all OS:

https://github.com/TerraME/terrame/search?q=blank+space&unscoped_q=blank+space

Note, TerraME must be installed on 'Application' directory on Mac.

How do you get that error?

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo can the user select where TerraME will be installed on Mac?

**Comment by avancinirodrigo** [comment]
> @avancinirodrigo can the user select where TerraME will be installed on Mac?

It can't. But, the user can copy to another dir before to installer on /Application, it would be unusual for mac users.

**Comment by pedro-andrade-inpe** [comment]
Ok, I'll wait to see if this happens again.
