### ISSUE TITLE
decimal separator in Charts

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#2356]
It seems that the decimal separator in both axis of a Chart use the current language in Windows. The problem is that all the other values follow English standard. Fix this.

**Comment by avancinirodrigo** [comment]
https://stackoverflow.com/questions/51408429/qwt-align-center-the-date-time-label-text-on-an-bottom-axis

**Comment by avancinirodrigo** [comment]
https://stackoverflow.com/a/26801054/3050042
