### ISSUE TITLE
empty shapefile

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#2361]
When one tries to open an empty shapefile as a CellularSpace it produces an internal error:

```
Error: attempt to index a nil value (field '?')
```
It should show: "The file is empty."

The code and the shapefile are: 
[error-empty-shape.zip](https://github.com/TerraME/terrame/files/5229256/error-empty-shape.zip)

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe 
Associated to #2347
