### ISSUE TITLE
bug in ~TaskManager

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#304]
~TaskManager has a bug with different situations. Because of that, part of it was commented to remove the bug. Fix it. The example below reproduces the bug if ~TaskManager has its lines uncommented.

```lua
        world = Cell{value = 3, value2 = 5}

        c = InternetSender{
            subject = world,
            select = {"value", "value2"},
            protocol = "udp"
        }
```

**Comment by pedro-andrade-inpe** [comment]
Similar to #55

**Comment by avancinirodrigo** [comment]
The error does not happen to me.

**Comment by avancinirodrigo** [comment]
If the current destructor is removed an error is generated beyond the already known.
This refers to Linux, I don't know about the Mac.

Console output:
QWaitCondition: cv destroy failure: Device or resource busy
QWaitCondition: mutex destroy failure: Device or resource busy

**Comment by pedro-andrade-inpe** [comment]
Unnecessary due to observer rollback
