### ISSUE TITLE
Compile TerraME in Windows

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#331]
Compile TerraME in Windows

**Comment by pedro-andrade-inpe** [comment]
It seems that the user cannot set the instalation folder. Put it back.

**Comment by pedro-andrade-inpe** [comment]
Display a message in the end of the installation telling that TerraME was successfully installed.

**Comment by avancinirodrigo** [comment]
Install MinGW
use MinGW Installation Manager
Use the site's instructions for correct installation
Install mingw32-base
Install mingw-developer-toolkit
Install mingw32-lua (all)
Install mingw32-libz (all)
Install mingw32-gcc-g++ (all)
Include MinGW dirs /include, /bin and /lib in Windows Path environment variable
Install CMake
Build & Install TerraLib
Install a SVN client (e.g. TortoiseSVN)
Create a directory to compile TerraLib, e.g. C:\Users\{user}\TerraLib 
Get build and src from SVN repository
https://svn.dpi.inpe.br/terralib/tags/v-4-2-0/src 
https://svn.dpi.inpe.br/terralib/tags/v-4-2-0/build
In the file build/cmake/CMakeLists.txt, replace the following:
OPTION (BUILD_TERRAVIEW "Build also terraView?" ON )
to OFF
In the file build/cmake/tlib_projs/terralib/CMakeLists.txt, replace the following:
OPTION (TE_DXF_ENABLED "Add dxf support?" ON)
OPTION (TE_SPL_ENABLED "Add spl support?" ON)
OPTION (TE_QT3_DRIVERS_ENABLED "Add qt3 drivers support?" ON)
OPTION (TE_QWT3_DRIVERS_ENABLED "Add qwt-qt3 drivers support?" ON)
to OFF
Install Jpeg
follow the instructions on the site (MinGW with MSYS): http://stackoverflow.com/questions/12652178/compiling-libjpeg 
Don’t forget to include jpeg directories in your development environment (MinGW’s paths)
Install Tiff
Idem’s Jpeg 
Install Proj4
Idem’s Jpeg
Install GeoTIFF 
Idem’s Jpeg
Add support to Jpeg and Zlib:
./configure --with-jpeg=yes --with-zlib=yes --prefix=<<path/to/install>>
Put on MinGW paths
Install GDAL
Idem’s Jpeg 
obs: if an error occurs of the type “undefined reference”, use the command:
./configure --prefix=<<path/to/install>> --with-png=internal --with-jpeg=internal --with-geotiff=internal --with-libtiff=internal
Install MySQL DB
Install MySQL Connector C
	obs: Install MySQL Connector C x32 too if your installation is x64
Install MySQL Utilities
Create a dir for build TerraLib (e.g. ./build/cmake/tlib-4.2.0)
Include C:\MinGW\bin, /include and /lib in Windows Path envenvironment variable
Use Prompt, enter in dir and run:
	cmake -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<<some/path>> -DGDAL_LIBRARY=C:\MinGW\bin\libgdal-1.dll -DGeoTIFF_INCLUDE_DIR=C:\MinGW\include  -DMYSQL_INCLUDE_DIR="C:\Program Files (x86)\MySQL\MySQL Connector C 6.1\include" ..
	mingw32-make
	mingw32-make install
Copy the content of dirs /include, /lib and /bin to MinGW paths
Remove MinGW paths from Path envenvironment variable to continue
Build & Install TerraME
Install Git client (e.g. Source Tree)
Clone the TerraME on Git: https://github.com/TerraME/terrame.git
Install Qt5 (choose the version according to your version of gcc mingw)
Include Qt5 dirs /include, /bin and /lib in Windows Path environment variable
Creating a system environment called LIBRARY_PATH and setting it to C:\Qt\5.1.1\mingw48_32\bin
Install Qwt
Use MSYS Shell
qmake qwt.pro
make
make install
Include Qwt /include and /lib in Windows Path envenvironment variable
Build and Install QtLua
Use Prompt:
 cmake -G"MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=<<some/path>> ..
mingw32-make
		mingw32-make install
Put on MinGW paths
Build and Intall QtLua-Extras
Use Prompt:
cmake -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<<some/path>> <<path/to/dir/CMakeLists>>
mingw32-make
mingw32-make install
Put on MinGW paths
Build and Install RandomLib
Use Prompt:
cmake -G"MinGW Makefiles"
 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS:STRING="-D__NO_INLINE__"  -DCMAKE_
INSTALL_PREFIX=<<some/path>> <<path/to/dir/CMakeLists>>
mingw32-make
mingw32-make install
Create RandomLib dir (e.g. C:\RandomLib) and copy the content of dirs /lib and /bin from the build dir to created dir. If you prefer, put on MinGW paths
Build and Intall Protobuf
Idem’s Jpeg
Don’t forget to include Protobuf directories in your development environment
Finally, Build and Intall TerraME
User Prompt:
cmake -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DQTLUA_INCLUDE_DIR=C:\MinGW\include -DQTLUAEXTRAS_INCLUDE_DIR=C:\MinGW\include -DQWT_INCLUDE_DIR=C:\Qwt-6.1.2\include -DTERRALIB_KERNEL_INCLUDE_DIR=C:\MinGW\include\terralib\kernel -DTERRALIB_MYSQL_INCLUDE_DIR=C:\MinGW\include\terralib\drivers\MySQL -DTERRALIB_JPEG_INCLUDE_DIR=C:\MinGW\include\terralib\drivers\libjpeg -DTERRALIB_LIBRARIES=C:\MinGW\lib -DCMAKE_INSTALL_PREFIX=<<some/path>> <<path/to/dir/CMakeLists>>
	mingw32-make
	mingw32-make install (bug)
It is necessary to copy some dlls in the same directory where the terrame.exe is:
	libmysql.dll
	libqtlua.dll (<<..terrame>>/dependencies/libqtlua-2.0/src)
	qtluae.dll (renamed from libqtluae.dll)
	libstdc++6.dll (this dll may have conflict with other same installed on the system, it was used:C:\Qt\5.4\mingw491_32\bin)
Create TME_PATH in system’s environment variable
If you preffer to use Qt Creator “Run cmake”:
obs: configure Tools > Options > Kit to your system MinGW
-DCMAKE_BUILD_TYPE=Release -DLUA_INCLUDE_DIR=C:\MinGW\include -DQTLUA_INCLUDE_DIR=C:\MinGW\include -DQTLUAEXTRAS_INCLUDE_DIR=C:\MinGW\include -DQWT_INCLUDE_DIR=C:\Qwt-6.1.2\include -DQWT_LIBRARY=C:\Qwt-6.1.2\lib\qwt.dll -DTERRALIB_KERNEL_INCLUDE_DIR=C:\MinGW\include\terralib\kernel -DTERRALIB_MYSQL_INCLUDE_DIR=C:\MinGW\include\terralib\drivers\MySQL -DTERRALIB_JPEG_INCLUDE_DIR=C:\MinGW\include\terralib\drivers\libjpeg -DJPEG_INCLUDE_DIR=C:\MinGW\include -DJPEG_LIBRARY=C:\MinGW\bin\libjpeg-9.dll -DPROTOBUF_INCLUDE_DIR=C:\MinGW\include -DPROTOBUF_PROTOC_EXECUTABLE=C:\MinGW\bin\protoc.exe -DPROTOBUF_LIBRARY=C:\MinGW\bin\libprotobuf-9.dll -DMYSQL_LIBRARY="C:\Program Files\MySQL\MySQL Connector.C 6.1\lib\libmysql.dll" -DMYSQL_INCLUDE_DIR="C:\Program Files\MySQL\MySQL Connector.C 6.1\include" 
Give full permission to the directory where the terrame.exe was generated

Dependencies Versions
Software
Version
Source
mingw-get
0.6.2-beta-20131004-1
http://www.mingw.org/category/wiki/download 
mingw32-base
2013072200
MinGW Installation Manager
mingw32-lua
5.2.0-1
MinGW Installation Manager
mingw32-libz
1.2.8-1
MinGW Installation Manager
mingw32-gcc-g++
4.8.1-4
MinGW Installation Manager
Cmake
3.2.3
http://www.cmake.org/download/ 
TerraLib
4.2.0
https://svn.dpi.inpe.br/terralib/tags/
Jpeg
9.1
http://lrn.no-ip.info/other/mingw/mingw32/jpeg/ 
Tiff
4.0.4
http://download.osgeo.org/libtiff/ 
Proj4


https://github.com/OSGeo/proj.4 
GeoTIFF
1.4.1
http://trac.osgeo.org/geotiff/
GDAL
1.11.2
https://trac.osgeo.org/gdal/wiki/DownloadSource 
MySQL Community Server
5.6.25
 https://dev.mysql.com/downloads/mysql/ 
MySQL Connector/C
6.1.6
https://dev.mysql.com/downloads/connector/c/ 
MySQL Utilities
1.5.4
https://dev.mysql.com/downloads/file.php?id=455806 
TerraME


https://github.com/TerraME/
Qt
5.1.1
https://www.qt.io/download-open-source/ 
Qt Creator
3.4.1
https://www.qt.io/download-open-source/#section-2 
Qwt
6.1.2
http://sourceforge.net/projects/qwt/files/qwt


QtLua
2.0
Use the specific contained in TerraME/dependencies
QtLua-Extras


https://github.com/gqueiroz/qtluae 
RandomLib
1.10
http://sourceforge.net/projects/randomlib/files/distrib/ 
Protobuf
2.6.1
https://github.com/google/protobuf/releases
