### ISSUE TITLE
cpack: environment variables

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#415]
Investigate how cpack handle environmental variables to be used by the installer.

**Comment by avancinirodrigo** [comment]
Currently the setting is only for Mac

**Comment by pedro-andrade-inpe** [comment]
cpack will be replaced by CMake directly.

**Comment by avancinirodrigo** [comment]
Associeted to #934.

**Comment by avancinirodrigo** [comment]
TerraME no longer uses PackageMaker (deprecated) to generate the installer, currently it uses DragNDrop to generate DMG which isn't possible create environment variables. See #934 for more details.
