### ISSUE TITLE
cpack: install names

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#416]
Fix the "install names" from cpack. In the last installer, it was implemented as a separate script.

**Comment by avancinirodrigo** [comment]
That's high level information for me. I need more details.
Where's "install names"?

**Comment by pedro-andrade-inpe** [comment]
cpack will be replaced by CMake directly.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, If it works in Linux in Mac would be fixed?
In Windows cpack is not necessary.

**Comment by pedro-andrade-inpe** [comment]
Possibly not, as they have different commands for some linking purposes.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, install name would be the name of the installer? 
for ex. terrame-2.0.mac.dmg?

**Comment by pedro-andrade-inpe** [comment]
terrame-2.0.dmg
