### ISSUE TITLE
remove randomlib from TerraME

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#534]
Replace RandomLib with a Lua code.

**Comment by gilbertocamara** [comment]
Oi Pedro
      
      Funcionou?
      
      Gilberto
    
    On 22.06.15 16:25 , Pedro R. Andrade
      wrote:
    
    
      Replace RandomLib with a Lua code.
      —
        Reply to this email directly or view it
          on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
====================================================================
Prof. Dr. Dr.h.c. Gilberto Camara
National Institute for Space Research (INPE), Brazil
http://www.dpi.inpe.br/gilberto
=====================================================================

**Comment by pedro-andrade-inpe** [comment]
Oi Gilberto,

eu apenas cadastrei o ticket, ele não esta resolvido. É sobre isto que 
quero conversar com voce. Amanhã de tarde passo na sua sala.

um abraco,

Pedro


On 6/22/15 16:51, Gilberto Camara wrote:
>
>
>
>
>
> Oi Pedro
>
> Funcionou?
>
> Gilberto
>
> On 22.06.15 16:25 , Pedro R. Andrade
> wrote:
>
>
> Replace RandomLib with a Lua code.
> —
> Reply to this email directly or view it
> on GitHub.
>
>
>
>
>
>
>
>
>
> --
> ====================================================================
> Prof. Dr. Dr.h.c. Gilberto Camara
> National Institute for Space Research (INPE), Brazil
> http://www.dpi.inpe.br/gilberto
> =====================================================================
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TerraME/terrame/issues/534#issuecomment-114237146>.
>

-- 
Pedro R. Andrade, Dr.
Earth System Science Center (CCST)
National Institute for Space Research (INPE)
Sao Jose dos Campos, Brazil

**Comment by gilbertocamara** [comment]
Oi Pedro
      
      Eu fiz o código e tenho pronto. Acho que fiz um commit. 
      
      Gilberto
    
    On 22.06.15 17:02 , Pedro R. Andrade
      wrote:
    
    Oi Gilberto,
      
      eu apenas cadastrei o ticket, ele não esta resolvido. É sobre isto
      que 
      quero conversar com voce. Amanhã de tarde passo na sua sala.
      
      um abraco,
      
      Pedro
      
      
      On 6/22/15 16:51, Gilberto Camara wrote:
      >
      >
      >
      >
      >
      > Oi Pedro
      >
      > Funcionou?
      >
      > Gilberto
      >
      > On 22.06.15 16:25 , Pedro R. Andrade
      > wrote:
      >
      >
      > Replace RandomLib with a Lua code.
      > —
      > Reply to this email directly or view it
      > on GitHub.
      >
      >
      >
      >
      >
      >
      >
      >
      >
      > --
      >
      ====================================================================
      > Prof. Dr. Dr.h.c. Gilberto Camara
      > National Institute for Space Research (INPE), Brazil
      > http://www.dpi.inpe.br/gilberto
      >
      =====================================================================
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/TerraME/terrame/issues/534#issuecomment-114237146>.
      >
      
      -- 
      Pedro R. Andrade, Dr.
      Earth System Science Center (CCST)
      National Institute for Space Research (INPE)
      Sao Jose dos Campos, Brazil
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
====================================================================
Prof. Dr. Dr.h.c. Gilberto Camara
National Institute for Space Research (INPE), Brazil
http://www.dpi.inpe.br/gilberto
=====================================================================
