### ISSUE TITLE
Error running terrame command without parameters in Windows OS

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#556]
\>terrame
PANIC: unprotected error in call to Lua API (C:\Users\root\TerraME\Git\terrame\b
in\lua\pmanager.lua:29: QtLua::ValueBase:The value contains a null `QtLua::UserD
ata' reference.)

**Comment by avancinirodrigo** [comment]
Someone is having the same problem: http://lists.nongnu.org/archive/html/libqtlua-list/2015-06/msg00000.html

**Comment by pedro-andrade-inpe** [comment]
It is also working in Mac.
