### ISSUE TITLE
build TerraME installer in Mac using  pkgbuild and productbuild

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#580]
build TerraME installer win Mac using  pkgbuild and productbuild, tools that replace PackageMaker. Observe the problems in the previous version of the installer #558.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, I think this issue is now invalid as we are now using cmake, isn't it?

**Comment by avancinirodrigo** [comment]
yes, it's invalid now.
