### ISSUE TITLE
sudo make install fails

### ISSUE THREAD

**Issue by albhasan** [TerraME/terrame#588]
Hi
I fail to compile from source using Ubuntu, it seems I am missing some documentation files. Can you help me? I did the following:

>git clone https://github.com/TerraME/terrame.git
>cd terrame/build/cmake
>cmake .
>sudo make install 

And it goes well until it gives this message:

>CMake Error at cmake_install.cmake:54 (file):
>  file INSTALL cannot find
>  "/media/data/ghProjects/terrame/build/cmake/../../base/doc".
>make: *** [install] Error 1

I am running Ubuntu 14.04.2 LTS; my kernel is 

>uname -a 
>Linux ******** 3.16.0-37-generic #51~14.04.1-Ubuntu SMP Wed May 6 15:23:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Thanks!

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, I this it is unnecessary to tell cmake to install the doc folder of base package, as it is already within base. The second if below should not be necessary.

```bash
if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/packages/base/" TYPE DIRECTORY FILES "/Users/pedro/github/terrame/build/cmake/../../base/")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/doc/" TYPE DIRECTORY FILES "/Users/pedro/github/terrame/build/cmake/../../base/doc/")
endif()
```

**Comment by avancinirodrigo** [comment]
Hi Alber,
While not solve the problem, you can go working with the directory [terrame]/bin generated with make. Point your variable TME_PATH for it.
