### ISSUE TITLE
remove mdb databases from TerraME

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#691]
remove mdb databases from TerraME as they are no longer supported.

**Comment by avancinirodrigo** [comment]
This issue needs review because TerraLib5 supports mdb.

**Comment by tiagogsc** [comment]
It is a good idea replace Access by SQLite dependences because Access only
works in Windows. Microsoft doesn't support Access in other platforms,
nobody does.
Em 16/11/2015 11:49, "Rodrigo Avancini" <notifications@github.com> escreveu:

**Comment by avancinirodrigo** [comment]
The TerraLib 5 workes with mdb transparently. Including already implemented. But if need to remove, I can do this. Please, @pedro-andrade-inpe  review this issue.

**Comment by pedro-andrade-inpe** [comment]
Everything related to TerraLib needs to be extensively tested in TerraME, as they do not have a test methodology as strict as ours. It is not good to have tests that need to be executed in only one operational system. At least for now, I also believe it is better not to support MDB databases in TerraME.
