### ISSUE TITLE
Error message on input data screen must be returned to the same screen 

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#702]
That shold be a guideline of usability.
E.g.:
Input connection parameters GUI, after error, returns to the main window, but should be returns to the same screen. 

A best resource for that would be asynchronous validation. Idea to future design GUI.

**Comment by pedro-andrade-inpe** [comment]
Enumerate here all possible errors in the graphical interface and verify each of them.

**Comment by pedro-andrade-inpe** [comment]
The screen to install a package from the repository should not be closed after installing a given package.
