### ISSUE TITLE
Implement scheduling functionalities in Lua side

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#733]
Scheduling functionalities is currently implemented in the C++ side. It has some disadvantages if compared to a pure Lua implementation:
1) Scheduler operations usually consume few time along the simulation of a model. What is really time-consuming is implemented inside the actions of Events. In this sense, having scheduler operations in Lua would not make much difference in terms of simulation time.
2) Scheduling functionalities need to go from C++ to Lua frequently. Moving from one side to another is inefficient if compared to a strict Lua implementation (see #479).
3) it is necessary to create a new copy of the `Event` each time an action will be executed.
4) The implementation of scheduling functionalities is one of the most difficult code in C++ (mainly because of 2 and 3).
5) Events sometimes have type `Event` but sometimes they are `userdata`.

Moving the implementation to Lua side would also help to solve the following issues: #23, #188, #189, #190, #192, #195, #198, #241, #255, #370, #371, #666, #674, #675, #673.

**Comment by tiagogsc** [comment]
It is worth to think that a c++ simulator with no scheduling algorithm is
incomplete. It becomes a virtual machine that doesnt execute processes.
Taking the scheduler to Lua side may bring a huge impact to the development
of parallel and distributed versions of TerraME.
Em 08/10/2015 10:58, "Pedro R. Andrade" <notifications@github.com> escreveu:

**Comment by pedro-andrade-inpe** [comment]
The C++ simulator is not isolated from Lua. In fact, they are strongly coupled. Every time the scheduling algorithm needs to execute an action, it creates a Lua Event by manipulating the stack and then asks Lua to execute the action.

The implementation of scheduling functionalities in Lua requires less than 50 lines of code for Timer and Environment together. Maintaining such code is trivial and it can be extended to a parallel version written in C++ if needed. Note that this solution will help to remove some tricky pieces of Lua code (and tests) and also to close more than ten issues.

Anyway, this implementation will not remove the C++ code anymore. It will stay there and in the future we can think in giving the opportunity for the user to choose between Lua and C++ implementations (see #172).

**Comment by tiagogsc** [comment]
I agree that this is a better approach. However, it is important to
highlight that the c++ simulator is isolated from the lua based one. Only
the Lua/C++ interface (or wrapper), at the above level of abstraction
(inheritance), knows the Lua stack. Currently, the c++ core provides data
structures to represent all TerraME types except those for ABM modeling
(mostly made in Lua), scheduling algorithms, simulation algorithms, and an
architecture that guarantee coherence to all computations.

In this context, it would be important to consider why in the game industry
companies keep their game/simulation engine in C++ and script applications
in Lua.  I haven´t seen any moving in the opposite direction.

I think that points to decide what to have in Lua or in C++ need of deep
appreciation. Maybe we may promote a better forum for dealing with this
kind of issues. This kind of subject is so important and impacts so much
all we have done until now, that I do believe the it diserves some
meetings.

--
Prof. Dr. Tiago Garcia de Senna Carneiro
TerraLAB - Earth System Modelling and Simulation Laboratory
Computer Science Department, UFOP - Federal University of Ouro Preto

Campus Universitário Morro do Cruzeiro, Ouro Preto - MG, Brazil, 35400-000
+55 31 3559 1692   +55 31 3559 1253
www.terralab.ufop.br   www.decom.ufop.br

2015-10-09 15:13 GMT-03:00 Pedro R. Andrade <notifications@github.com>:

**Comment by pedro-andrade-inpe** [comment]
It is a good idea to include this topic in the next meeting. We will further investigate this so we can have something concrete to guide our discussion.
