### ISSUE TITLE
Terralib 5 doesn't compile with Lua binding

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#748]
With this it isn't possible to continue the upgrade.

**Comment by pedro-andrade-inpe** [comment]
You should put the reason why it does not work here.

**Comment by avancinirodrigo** [comment]
I'm afraid that only terralib team would know this question.

**Comment by avancinirodrigo** [comment]
The terralib needs [SWIG](http://www.swig.org/download.html) for to compile the bindings. It works now.
