### ISSUE TITLE
add the missing examples from terrame web page

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#760]
Add the missing examples from http://www.terrame.org/doku.php?id=examples130.

**Comment by tiagogsc** [comment]
There are some cool examples at
http://www.terralab.ufop.br/dokuwiki/doku.php?id=terralab:curso:envsoft:projectoutline
.
They are also presented according to a very cool templated page.

--
Prof. Dr. Tiago Garcia de Senna Carneiro
TerraLAB - Earth System Modelling and Simulation Laboratory
Computer Science Department, UFOP - Federal University of Ouro Preto

Campus Universitário Morro do Cruzeiro, Ouro Preto - MG, Brazil, 35400-000
+55 31 3559 1692   +55 31 3559 1253
www.terralab.ufop.br   www.decom.ufop.br

2015-10-23 16:36 GMT-02:00 Pedro R. Andrade <notifications@github.com>:

**Comment by pedro-andrade-inpe** [comment]
The examples available at terralab webpage are being implemented in packages ca and logo
https://github.com/pedro-andrade-inpe/logo/issues
https://github.com/pedro-andrade-inpe/ca/issues
