### ISSUE TITLE
Layer:fill

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#788]
Implement a CellularLayer:fillCells to fill the cells of cellular spaces. This issue should be implemented with only a single strategy (according to the documentation already available in the package). Implement basic and alternative tests. Other strategies need to be implemented in separated issues.

**Comment by pedro-andrade-inpe** [comment]
The process to implement each strategy will be as follows:
1. @pedro-andrade-inpe will implement a Lua test for such strategy.
2. @avancinirodrigo will implement the internal function with a call to TerraLib.
3. @pedro-andrade-inpe will create a snapshot and verify if the result is correct. If ok then the ticket is closed, otherwise go back to step 2.

**Comment by pedro-andrade-inpe** [comment]
terralib5/src/terralib/attributefill

Class VectorToVectorMemory
- empty constructor
- setInput to set input and reference layers (AbstractLayerPtr)
- setParams: Property* (parameters) and operation (described in Enum.h)
- setOutput: DataSource, new attribute name
- run()

Raster uses the enum available in te::stat

**Comment by avancinirodrigo** [comment]
Vectorial operations completed. Released to verification.

**Comment by avancinirodrigo** [comment]
Raster operations completed. Released to verification.

**Comment by avancinirodrigo** [comment]
VectorToVector enum:

```cpp
/*!
  \file terralib/geometry/Enums.h
*/

    /*!
      \enum OperationType

      \brief Define grouping operations type.
    */
    enum OperationType
    {
      VALUE,
      MIN_VALUE,
      MAX_VALUE,
      MEAN,
      SUM,
      COUNT,
      VALID_COUNT,
      STANDARD_DEVIATION,
      VARIANCE,
      SKEWNESS,
      KURTOSIS,
      AMPLITUDE,
      MEDIAN,
      VAR_COEFF,
      MODE,
      HIGHEST_OCCURRENCE,
      HIGHEST_INTERSECTION,
      PERCENT_CLASS,
      MIN_DISTANCE,
      PRESENCE,
      WEIGHTED,
      WEIGHTED_SUM,
      PERCENT_EACH_CLASS,
      PERCENT_TOTAL_AREA
    };
```

**Comment by avancinirodrigo** [comment]
RasterToVector enum:

```cpp
/*!
  \file terralib/statistics/core/Enums.h
*/

    /*!
      \enum StatisticalSummary

      \brief Define grouping functions type.
    */
    enum StatisticalSummary
    {
      MIN_VALUE,                  //!< Minimum value.
      MAX_VALUE,                  //!< Maximum value.
      MEAN,                       //!< Mean.
      SUM,                        //!< Sum of values.
      COUNT,                      //!< Total number of values.
      VALID_COUNT,                //!< Total not null values.
      STANDARD_DEVIATION,         //!< Standard deviation.
      VARIANCE,                   //!< Variance.
      SKEWNESS,                   //!< Skewness.
      KURTOSIS,                   //!< Kurtosis.
      AMPLITUDE,                  //!< Amplitude.
      MEDIAN,                     //!< Median.
      VAR_COEFF,                  //!< Coefficient variation.
      MODE,                       //!< Mode.
      PERCENT_EACH_CLASS_BY_AREA, //!< Percente of each class by area.
      PERCENT_TOTAL_AREA          //!< Percente of total area.
    };
```

**Comment by pedro-andrade-inpe** [comment]
Fill is working properly. The remaining operations are bugs or depend on TerraLib.
