### ISSUE TITLE
fillCell vectorial with strategy "average"

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#801]
Implement strategy "average" for fillCell with vectorial data. #788.Note that this strategy will use two internal TerraLib functions, MEAN and WEIGHTED.

**Comment by avancinirodrigo** [comment]
What is the criteria to use MEAN or WEIGHTED?

**Comment by pedro-andrade-inpe** [comment]
area = false -> MEAN
area = true -> WEIGHTED
