### ISSUE TITLE
fillCell raster with strategy "percentage"

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#808]
Implement strategy "percentage" for fillCell with raster data. #788.Note that this strategy gets only integer or string in the input attribute and creates an attribute for each available value.

**Comment by pedro-andrade-inpe** [comment]
There are two bugs here:

1. It seems that it is using R from RGB values instead of the real value for band 0.
2. Some cells have more than 100% of coverage, which is impossible.

**Comment by pedro-andrade-inpe** [comment]
Solving this issue needs an update to branch TerraLib develop.

**Comment by avancinirodrigo** [comment]
I'm needing resolution the issue #1052 for upgrade to new branch.

**Comment by pedro-andrade-inpe** [comment]
This issue requires branch 5.2 in TerraLib to be open. They are going to to this as long as 5.1.2 is released.

**Comment by avancinirodrigo** [comment]
Associated to #1556 now.

**Comment by pedro-andrade-inpe** [comment]
It is already working properly.
