### ISSUE TITLE
fillCell vectorial with strategy "nearest"

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#814]
Implement strategy "nearest" for fillCell with vectorial data. This strategy should use the attribute value of the closest object as new value for the cell.

**Comment by avancinirodrigo** [comment]
There is a "value" operation in TerraLib. I'm not understand this issue very well .

**Comment by pedro-andrade-inpe** [comment]
See the comment above: "Note that both strategies are not implemented in TerraLib.". This issue is to be solved in version 2.1, not now.

**Comment by pedro-andrade-inpe** [comment]
This strategy will be implemented in package gpm, as it is more related to connectivity.
