### ISSUE TITLE
rethink fillCell concepts and operations

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#826]
The current names for fillCell operations is the same of previous TerraLib version. Rethink the adopted names. For example:

- `coverage` instead of `percentage`?
- `mode` instead of `majority`?

**Comment by pedro-andrade-inpe** [comment]
Why not using `Layer` instead of `CellularLayer`. It is possible to use fill cell operations with any geometry, not only cellular data. Note that once the concept is released it will be difficult to change its name.

**Comment by avancinirodrigo** [comment]
I think it is a good idea. There is a little ambiguity that would removed.

**Comment by pedro-andrade-inpe** [comment]
If the name changes from `CellularLayer` to `Layer`, then we would need to change `fillCells` to `fillAttribute` and consequently the name of the package. What would be the new name for the package? terralib?

**Comment by avancinirodrigo** [comment]
Users don't know about terralib behind that, but maybe they know about GIS system and their operations.

**Comment by pedro-andrade-inpe** [comment]
Other changes: remove package fillcell and move everything to terralib. Rename `fillcells` function to simply `fill` as it will be possible to fill not only cells.
