### ISSUE TITLE
fillCell with strategy median

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#830]
Think about the necessity of a strategy median for quantitative data in fillCell.

**Comment by pedro-andrade-inpe** [comment]
#890

**Comment by pedro-andrade-inpe** [comment]
Implement for both raster and vector data.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, Could you please write here the operation documentation to layer.
I am confusing about 'average' and this operation.

**Comment by pedro-andrade-inpe** [comment]
The median is the midpoint of a frequency distribution of observed values.
