### ISSUE TITLE
Could datasources in file project to have relative path instead absolute? 

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#831]
If cannot, the users will have problems when they need to reuse the project in other computers or share them.

**Comment by pedro-andrade-inpe** [comment]
In fact, it is necessary to have a function `Project:export()` to save the project and all the data it uses into a single zip file. All the data should be put together into a single folder (possibly each layer could be put into separate folders inside this one). This would require to change the paths in the project itself to make it consistent. When copied to another machine, the user can simply unzip the file and use the project as it is. In principle, this function should be implemented on the TerraLib side, but we can do so easily in Lua.

**Comment by pedro-andrade-inpe** [comment]
This should be written in #890.
