### ISSUE TITLE
FillCell:Utils

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#842]
I created some functions that can be used in the base. @pedro-andrade-inpe check please in https://github.com/TerraME/terrame/commit/d9804a9ebd2c0c79afdb89653dbc1902bb2ac507.
If can, I will move them to there.

**Comment by pedro-andrade-inpe** [comment]
Yes, we can rethink about FillCell:Utils after finishing fillCell operations.

**Comment by pedro-andrade-inpe** [comment]
Let's keep them there and think more about it in the future.
