### ISSUE TITLE
create a dictionary for TerraME

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#849]
Create a dictionary for TerraME in a wiki page. It must describe the words extensively used in TerraME and their meanings.

**Comment by pedro-andrade-inpe** [comment]
@tiagogsc @avancinirodrigo 
There are several inconsistencies in the documentation of TerraME because of the lack of a dictionary. I am writing this dictionary at https://github.com/TerraME/terrame/wiki/dictionary.  Suggestions can be put directly into this issue. Maybe we can schedule a meeting in February to discuss this.

**Comment by tiagogsc** [comment]
Cool
