### ISSUE TITLE
Checking the assert is executed even if it is commented on Windows

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#853]
I'm putting `--SKIP` even that the assert is commented.

Comment some assert to reproduce.

**Comment by pedro-andrade-inpe** [comment]
Verifying SKIP is good for automatic releases, but it might not be interesting for the developer when solving a given issue.

**Comment by pedro-andrade-inpe** [comment]
It was a project decision to verify every commented assert if they have SKIP. See #823.

**Comment by pedro-andrade-inpe** [comment]
Whenever it is necessary to comment a set of asserts within a given function to be tested, two solutions are possible to be used to avoid getting errors in the tests:

1. Use a separate script just for the given problem, without needing to use `-test`.
2. Add an `end` at some point and put the rest of the tests in another (temporary) function.
