### ISSUE TITLE
Is possible there is -utest command?

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#854]
The `-test` command executes all tests, it include even examples. The examples supposes that all features of a package was built. It is not true when a package is being built. The `-utest` command would create a better separation level of tests and their goals.

**Comment by pedro-andrade-inpe** [comment]
The configuration file already make it possible. One can use `examples = false` to avoid executing examples. See https://github.com/TerraME/terrame/wiki/Packages#Tests for more information.
