### ISSUE TITLE
vector vs. non-named table

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#874]
In TerraME documentation, tables like

```lua
stab = {1, 3, 4, 5, 8}
```

are 35 times called `vector` and 20 times called `non-named table`. Use only a name for this. Keep in mind that tables with names are called `named tables` in the documentation.

**Comment by gilbertocamara** [comment]
I would like to propose that we use vector, to distinguish from "named tables".

**Comment by pedro-andrade-inpe** [comment]
What about array?

**Comment by gilbertocamara** [comment]
No, array usually means 2D organization. I believe "vector" suits the case better
