### ISSUE TITLE
Database connection needs 'encoding' argument in Layer

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#876]
Now this argument is using a default encoding, but users can to have problems because of the special characters. 
What would be a good alternative for this?

**Comment by pedro-andrade-inpe** [comment]
It is necessary to thing about a general solution for encoding in TerraME. Issue #659 is also related to this topic. See also http://lua-users.org/wiki/LuaUnicode.

**Comment by pedro-andrade-inpe** [comment]
Solve with #1782.
