### ISSUE TITLE
Review read/write Project xml functions

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#880]
The functions test some asserts in C++ that went made 'fake' code to run in Lua. Fix this.

**Comment by avancinirodrigo** [comment]
Review problem with release the file after read.

**Comment by pedro-andrade-inpe** [comment]
Is it important or can we move it to 2.1, @avancinirodrigo?

**Comment by avancinirodrigo** [comment]
it can be moved.

**Comment by avancinirodrigo** [comment]
Associated to #890.
