### ISSUE TITLE
Explict call to the terralib:finalize()

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#883]
TerraME must call finalize() expecitly. Investigate how make this transparently for user.

**Comment by pedro-andrade-inpe** [comment]
Add to terrame.lua _Gtme.execute(arguments) in the end of this function.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, this solution works in normal execution, but in `-test`not.

**Comment by pedro-andrade-inpe** [comment]
-test calls os.exit() explicitly in the end. Remove terralib also in terrame.lua, in the end of 

```lua
elseif arg == "-test" then
```

just before os.exit().
