### ISSUE TITLE
Terralib5 Report

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#890]
This issue is intended to list the problems found in the TerraLib.

My suggestion for to test if a problem is really on TerraLib:
Test firstly in the TerraME, if a problem is found, test in the TerraView, after that, if the problem occur too, it must be reported to TerraLib team.

**Comment by avancinirodrigo** [comment]
Raster to Vector run() not validade if layers intesect.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, I have already finished the report. Please review it and then we can have a meeting to discuss the remaining points.

**Comment by pedro-andrade-inpe** [comment]
There are some missing points in the report related to the integration of TerraME and TerraView using .tview files. @avancinirodrigo, could you write about it:

**Comment by pedro-andrade-inpe** [comment]
https://docs.google.com/document/d/1_yu9pUQItW8Hhb6fVppsx6c7zJ6-H4Oqii1uLtLhibg/edit

**Comment by pedro-andrade-inpe** [comment]
The presentation of this report occurred in 29-30 June 2016. Some of these issues are now in charge of TerraLib team and some of them will be implemented by our team.
[fillcell-terralib5-terrame.pdf](https://github.com/TerraME/terrame/files/343341/fillcell-terralib5-terrame.pdf)
