### ISSUE TITLE
Integrate CellularLayer and CellularSpace

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#899]
This issue depends on #898.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, how it will be this integration?

**Comment by pedro-andrade-inpe** [comment]
Example:

```lua
cs = CellularSpace{
       project = "cellular_layer_basic.tview",
       layer = "Sampa"
}

print(#cs)
```

**Comment by pedro-andrade-inpe** [comment]
Arguments to be removed: database, host, password, port, theme, where, user. Add a new dbType: "proj". Remove dbTypes mdb and mysql.

**Comment by avancinirodrigo** [comment]
We could change `dbType` to `source`, it is clearerest. The description of the `dbType` already imples to `source`.
```
data.dbType A string with the name of the data source. It tries to infer the data source
```

**Comment by pedro-andrade-inpe** [comment]
great!

**Comment by avancinirodrigo** [comment]
It missed some changes in C++.
