### ISSUE TITLE
Change the type of all C++ files to ASCII

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#90]
Change the type of all C++ files to ASCII, by removing special characters. Use

iconv -t ascii -f utf-8 Observer.lua > resp.txt

pedro:core pedro$ file *
agent.h:              UTF-8 Unicode English text, with CRLF line terminators
bridge.h:             ISO-8859 English text, with CRLF line terminators
cell.h:               UTF-8 Unicode English text, with CRLF line terminators
cellularSpace.h:      ISO-8859 English text, with CRLF line terminators
composite.h:          ISO-8859 English text, with CRLF line terminators
controlMode.h:        ISO-8859 English text, with CRLF line terminators
environment.cpp:      ASCII c program text, with CRLF line terminators
environment.h:        UTF-8 Unicode English text, with CRLF line terminators
event.cpp:            ISO-8859 c program text, with CRLF line terminators
event.h:              ISO-8859 English text, with CRLF line terminators
loadNeighborhood.h:   ISO-8859 c program text, with CRLF line terminators
luaAgent.h:           ISO-8859 English text
luaCell.cpp:          UTF-8 Unicode English text, with CRLF line terminators
luaCell.h:            ISO-8859 English text
luaCellIndex.h:       UTF-8 Unicode English text, with CRLF line terminators
luaCellularSpace.cpp: UTF-8 Unicode English text, with CRLF line terminators
luaCellularSpace.h:   UTF-8 Unicode English text
luaControlMode.h:     ISO-8859 English text, with CRLF line terminators
luaEnvironment.cpp:   ISO-8859 c program text, with CRLF line terminators
luaEnvironment.h:     UTF-8 Unicode English text
luaEvent.cpp:         ISO-8859 English text, with CRLF line terminators
luaEvent.h:           UTF-8 Unicode English text
luaFlowCondition.h:   UTF-8 Unicode English text, with CRLF line terminators
luaGlobalAgent.cpp:   ISO-8859 c program text, with CRLF line terminators
luaGlobalAgent.h:     UTF-8 Unicode English text, with CRLF line terminators
luaJumpCondition.h:   UTF-8 Unicode English text, with CRLF line terminators
luaLocalAgent.cpp:    ISO-8859 English text, with CRLF line terminators
luaLocalAgent.h:      UTF-8 Unicode English text, with CRLF line terminators
luaMessage.h:         ISO-8859 English text
luaNeighborhood.cpp:  ISO-8859 English text, with CRLF line terminators
luaNeighborhood.h:    UTF-8 Unicode English text, with CRLF line terminators
luaRandomUtils.h:     UTF-8 Unicode English text, with CRLF line terminators
luaRegion.h:          ISO-8859 English text, with CRLF line terminators
luaRule.h:            ISO-8859 English text, with CRLF line terminators
luaSociety.cpp:       UTF-8 Unicode English text, with CRLF line terminators
luaSociety.h:         UTF-8 Unicode English text
luaTimer.cpp:         UTF-8 Unicode c program text, with CRLF line terminators
luaTimer.h:           UTF-8 Unicode English text, with CRLF line terminators
luaTrajectory.cpp:    ISO-8859 c program text, with CRLF line terminators
luaTrajectory.h:      UTF-8 Unicode English text
luaUtils.cpp:         UTF-8 Unicode English text, with CRLF line terminators
luaUtils.h:           UTF-8 Unicode English text, with CRLF line terminators
luna.h:               ASCII c program text, with CRLF line terminators
message.h:            ISO-8859 English text, with CRLF line terminators
model.cpp:            ASCII c program text, with CRLF line terminators
model.h:              ISO-8859 English text, with CRLF line terminators
neighborhood.h:       UTF-8 Unicode English text, with CRLF line terminators
process.h:            ISO-8859 English text, with CRLF line terminators
reference.h:          ASCII c program text
region.h:             ISO-8859 English text, with CRLF line terminators
registryObjects.h:    UTF-8 Unicode English text, with CRLF line terminators
rule.h:               ISO-8859 English text, with CRLF line terminators
scheduler.h:          UTF-8 Unicode English text, with CRLF line terminators
society.h:            UTF-8 Unicode English text, with CRLF line terminators
strategy.h:           ISO-8859 English text, with CRLF line terminators
terrameGlobals.h:     ASCII text
terrameLua.cpp:       UTF-8 Unicode English text, with CRLF line terminators
terrameLua.h:         UTF-8 Unicode English text, with CRLF line terminators
terrameLua5_0.h:      Little-endian UTF-16 Unicode English text
terrameLua5_1.h:      UTF-8 Unicode English text, with CRLF line terminators
pedro:core pedro$

**Comment by avancinirodrigo** [comment]
on ../terrame/src
find . | xargs file			# show files and coding
find . | xargs dos2unix 		# remove CRLF line terminators
find . | xargs file | grep UTF-8	# show only UTF-8 files

**Comment by avancinirodrigo** [comment]
This issue was reopened because of the code's rollback.
