### ISSUE TITLE
enableGraphics() and disableGraphics()

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#903]
Implement two functions to disable and enable the graphical interface for the observers to be created. Using observers make the simulation very slow, and so if one wants to speedup the simulation it is better to remove them. However, removing the source code of the observers manually is not a good solution because the user might want to use them again in the future. Therefore, it is interesting to have a function to disable creating observers without removing Chart, Map, etc. from the interface. It should only stop with error if one calls save methods (as they would not work).

**Comment by tiagogsc** [comment]
What about users controlling interfaces update by notifying them in a
independent event with its own periodicity? For example, calling notify at
every 100 ticks.

Em Qui, 11 de fev de 2016 09:13, Pedro R. Andrade <notifications@github.com>
escreveu:

**Comment by pedro-andrade-inpe** [comment]
In this case the user would need to change the source code of the model in the same way. The idea of these functions is to get rid of any graphical interface without needing to change the source code of the model. The original demand for this issue is when one wants to simulate the same model with different parameters or repeat a simulation several times. In this case, the user does not want to see the output along a single simulation. What really matters is the final result of each execution of a model.
