### ISSUE TITLE
Create TerraLib package

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#904]
The terralib will be used in `fillcell` and `base`packages, therefore is necessary that it is decoupled for better use.

Depends #899.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo I think it is better to have data files stored in package fillcell instead of terralib. It is in fillcell where the scripts to manipulate the data will be stored.

**Comment by avancinirodrigo** [comment]
Terralib does not know fillcell, but the fillcell knows the terralib, so in terms of system "module" associations, it would be better. But, I could change that.

**Comment by avancinirodrigo** [comment]
note: both packages use the data.

**Comment by pedro-andrade-inpe** [comment]
So it is better to separate some data for terralib and some for fillcell. The data from Isabel must belong to fillcell.
