### ISSUE TITLE
Fix terralib version from API

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#905]
Currently, '-version' show terralib version by C++ level. Now is necessary get from Lua. Fix that.

**Comment by avancinirodrigo** [comment]
Depends #899.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, where I put this?
See in commit above.

**Comment by pedro-andrade-inpe** [comment]
There is a function called cpp_informations(), implemented in src/core/terrameLua.cpp, that is used by src/lua/terrame.lua in function version().

**Comment by avancinirodrigo** [comment]
Is not possible to use getPackage() or import() to load terralib package in terrame.lua.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, see above.
