### ISSUE TITLE
Function 'import()' does not check if a package is already imported

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#906]
See in fillcell:CellularLayer

```lua
if not isLoaded("terralib") then
	import("terralib")
end
```

Remove this validation and run the tests to reproduce.

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, see the new documentation of import() to be used to solve your issues.

**Comment by avancinirodrigo** [comment]
I removed the `if isLoaded...` so didn't work. As default is 'check = true' so I put `import("terralib")
```
Error: Package 'fillcell' could not be loaded: Error: Package 'terralib' is already loaded. 
```

**Comment by avancinirodrigo** [comment]
`check = false` works. It is confusing this function:

-- @arg check A boolean value indicating whether TerraME should verify if the
-- package **is already loaded (default is true)**. Setting this parameter
-- to false forces the package to be loaded again if it was already loaded. It
-- also avoids a warning indicating that the package was already loaded.

I think that it should not throws a error.
`if loaded` -> ok, good bye.. no problem..

**Comment by avancinirodrigo** [comment]
Ps: but, I don't know how much this behavior is important to Lua and its impacts.

**Comment by pedro-andrade-inpe** [comment]
The argument will be changed from check to reload. The description becomes simpler in this case: allow reloading the package.

**Comment by avancinirodrigo** [comment]
This implies that the users always need to reload because they don't know if a package is already loaded.

**Comment by pedro-andrade-inpe** [comment]
No. Only a warning is shown if the package is loaded when using import (if reload is not set). If necessary, the user can know if the package was already loaded using `isLoaded()`.

**Comment by avancinirodrigo** [comment]
So nothing changed..

**Comment by pedro-andrade-inpe** [comment]
In fact, it is different now:

`import(package)`: please import the package if it was not loaded before, otherwise show me a warning (as it was before).
`import(package, true)`: please import the package. do not care if was not loaded before.

**Comment by avancinirodrigo** [comment]
Why users would like a warning if package is already loaded?

**Comment by pedro-andrade-inpe** [comment]
The execution mode "strict" do many verifications in order to help the modeller to make the code as clean as possible. In this case, trying to load an already loaded package is an unnecessary line and could be removed (unless the user is trying to reload the package). This could be identified by the strict mode.

**Comment by avancinirodrigo** [comment]
This works to packages associated to base package, but in a scenery where there are a lot of packages with distinct associations, it will be hard determined when a package is loaded or not.
It violates a guideline of modularization where a module musn't not know about what has in other modules.
But again, if that is important to Lua is better to keep.
In other languages the semantics of import/include is diferent.
