### ISSUE TITLE
Change CellularSpace attribute names related row/col 

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#912]
TerraME uses x/y concept, but some attributes as maxRow/maxCol use matrix definition, those names are inconsistent.
Change no xMax, yMax, xMIn and yMin.

**Comment by avancinirodrigo** [comment]
Question @pedro-andrade-inpe :
In documentation col represents y and row represents x.
would it not be the contrary?

```lua
-- @output maxCol The maximum value of the attribute y of its Cells.
-- @output maxRow The maximum value of the attribute x of its Cells.
-- @output minCol The minimum value of the attribute y of its Cells.
-- @output minRow The minimum value of the attribute x of its Cells.
```

**Comment by pedro-andrade-inpe** [comment]
Col is x and row is y.
