### ISSUE TITLE
execute vs. run: different behaviours in execute functions

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#921]
Many TerraME types have `execute` methods: `Agent`, `Automata`, `Society`, `Timer`, `Environment`, `Model`, and possibly `Cell` and `CellularSpace`. However, such methods have different meaning.

For `Agent`, `Automata` and `Society`, it means "execute such object for one time step". For `Timer`, `Environment`, `Model`, it means "run the model until a given final time". As they have different semantics, how about changing the name of `execute` from `Timer`, `Environment`, and `Model` to `run`?
Additionally, `Model` also has an optional method called `step` with the same meaning of `Agent` group. It could be called `execute` instead. This update would also give more consistency to the behavior of type `Event`, as a `Model` being an `action` would call `execute`, in the same way of the other TerraME types (currently it calls `step`).

**Comment by pedro-andrade-inpe** [comment]
Comments, @gilbertocamara?

**Comment by gilbertocamara** [comment]
I support the idea of changing the execute() in the Model to run(). It will be much more consistent with the rest of TerraME syntax.
