### ISSUE TITLE
Review CellularSpace documentation 

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#923]
The CellularSpace now is integrated to the TerraLib5, there is some concepts that must be reviewed.

**Comment by pedro-andrade-inpe** [comment]
Which concepts need to be reviewed, @avancinirodrigo?

**Comment by avancinirodrigo** [comment]
Old concepts like usage.

**Comment by pedro-andrade-inpe** [comment]
ok, so it is only documentation, not *concepts*.

**Comment by pedro-andrade-inpe** [comment]
Update the documentation of CellularSpace:save as well.

**Comment by pedro-andrade-inpe** [comment]
Document also that synchronise does not affect `.geom`.
