### ISSUE TITLE
VectorToVector doesn't release shapefile after to process

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#927]
This problem impacts on the tests because not is possible clean up some shapefiles after use them.
It could impact in some future use.

**Comment by pedro-andrade-inpe** [comment]
Isn't it possible to clean the shapefiles before the process instead of after?

**Comment by avancinirodrigo** [comment]
Yes, and after release terralib is possible too.

**Comment by pedro-andrade-inpe** [comment]
Waiting for Ruan.

**Comment by pedro-andrade-inpe** [comment]
It seems that it works in some operations. Possibly it works for VectorToVector xor RasterToVector.

**Comment by pedro-andrade-inpe** [comment]
xor CellularSpace.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe it seems works in current beta-1, could you review Layer tests for clean the created files?

**Comment by pedro-andrade-inpe** [comment]
This is working properly!
