### ISSUE TITLE
RasterToVector - problem with SRID

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#928]
The RasterToVector doesn't work.
The problem is associated to the SRID.
Waiting for solution from TerraLib Team.

**Comment by avancinirodrigo** [comment]
Issues associeted #890 #882.

**Comment by avancinirodrigo** [comment]
This problem happens when use `percentage` operation too. In the TerraView there is not this operation to raster, so is not possible to test there.

**Comment by pedro-andrade-inpe** [comment]
See the lines in packages/terralib/lua/TerraLib.lua (https://github.com/TerraME/terrame/commit/5e2155880ec4963fa9ad496cdb4b4e4920fb103a)


```lua
 -	if (fromLayer:getSRID() == 0) or (toLayer:getSRID() == 0) then
 -		customError("Input layer with invalid SRID information.")
 +	if (fromLayer:getSRID() == 0) or (toLayer:getSRID() == 0) then -- TODO: REVIEW
 +		--customError("Input layer with invalid SRID information.")
```

**Comment by pedro-andrade-inpe** [comment]
This problem does not exist anymore in TerraLib. However, it is important to register here that GDAL has changed its proj4 descriptions for some SRIDs. Therefore, some projections might not be recognised and will be managed as undefined.
