### ISSUE TITLE
Create directory 'functional' to tests

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#946]
@pedro-andrade-inpe, I'm thinking about create functional directory to put /basic and /alternative that are at the root test directory. This would be good because when we need only to test without database, it would be possible.
Like this:
```
test
    - functional
        - basic
        - alternative
    - database
        - basic
        - alternative
    - others
    .
    .
    . 
```

**Comment by pedro-andrade-inpe** [comment]
Which package are you talking about?

**Comment by avancinirodrigo** [comment]
For while `fillcell` and `terralib`.

**Comment by pedro-andrade-inpe** [comment]
The `base` package has four directories: core, database, internal, and observer. Possibly we can use core instead of functional? Or change the name core to functional in base as well?? We only need to keep consistency in the names.

**Comment by avancinirodrigo** [comment]
I think that name `core` is associated to source, but in tests we need to look as a tester, in which `functional` makes more sense.
For example, to tester:
core is functional
database is integration
observer is gui

But `functional` instead `core`is enough.

**Comment by pedro-andrade-inpe** [comment]
OK, so please change the name `core` to `functional` in base package too as part of this issue.
