### ISSUE TITLE
Customize error when the posgres is not installed

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#947]
The message that come of the terralib does not match to especific problem.

Associeted to #897

**Comment by avancinirodrigo** [comment]
TerraLib doesn't differentiate this error from incorrect port error, the messages are the same.
Associeted to #890.

**Comment by pedro-andrade-inpe** [comment]
Well, possibly the best error message is to simply say that it was not possible to connect. Checking if it was installed is not enough because the user might have installed but the process is not running, and so it gets difficult to have a more elaborated error message.

**Comment by pedro-andrade-inpe** [comment]
Which message is currently shown?

**Comment by pedro-andrade-inpe** [comment]
@avancinirodrigo, see the question above.

**Comment by avancinirodrigo** [comment]
See in alternative port test, the message is the same.
