### ISSUE TITLE
TerraME cannot read postgre layers from TerraView

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#948]
The opposite works.
Investigate field `PG_NEWDB_NAME` because TerraView doesn't use it.

**Comment by avancinirodrigo** [comment]
Associeted to #896

**Comment by avancinirodrigo** [comment]
Although TerraView doesn't use `PG_NEWDB_NAME`, it works with the field.
The problem seems that is associated with #929 and #928, some problem in the SRID and CellularSpace.
If the cellular space is created in TerraME, everything works.
So the integration needs more manual tests after resolution of the SRID.

**Comment by pedro-andrade-inpe** [comment]
#890.
