### ISSUE TITLE
Problems with paths in project file from TerraView

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#949]
Is necessary converter the paths symbols like %3%A.

Associeted to #896

**Comment by pedro-andrade-inpe** [comment]
See if we can have a unique solution that could be used also for `-showdoc`, that does the following:

```lua
        docpath = "file:///".._Gtme.makePathCompatibleToAllOS(docpath)
        docpath = string.gsub(docpath, "%s", "%%20")
```

**Comment by avancinirodrigo** [comment]
It seems that Uri is more complex:
```lua
local function decodeUri(str)
	str = string.gsub(str, "+", " ")
	str = string.gsub(str, "%%(%x%x)",
			function(h) return string.char(tonumber(h,16)) end)
	str = string.gsub(str, "\r\n", "\n")
	  
	return str	
end
```

**Comment by pedro-andrade-inpe** [comment]
OK. I will just link this issue to #561 in case of needing more complex decoding if some bug is found related to showdoc in Windows.
