### ISSUE TITLE
Document build process 2.0

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#975]
Review and document in Wiki the build process to compile terrame 2.0.

**Comment by avancinirodrigo** [comment]
Create README and INSTALL files that pointing to respective guides in wiki.

**Comment by pedro-andrade-inpe** [comment]
Documentation updated and available at https://github.com/TerraME/terrame/wiki/Building-and-Configuring. @raphaelrpl, use the documentation in this link to build TerraME when you configure the CI server.
