### ISSUE TITLE
Problem with Qt plugin on Mac

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#984]
Some related to `cocoa`
https://forum.qt.io/topic/25915/qt-5-0-and-failed-to-load-platform-plugin-cocoa

Try to add the plugins in installer to fix.

**Comment by pedro-andrade-inpe** [comment]
See how to pointing out the plugins directory in C++ at

http://www.tripleboot.org/?p=536#PluginDLLs
